# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build -c nvidia -c rapidsai -c numba -c conda-forge -c defaults .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
package:
  name: cudf
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ git_revision_count }}
  script_env:
    - CUDF_BUILD_NO_GPU_TEST

requirements:
  # use channel:
  #   - nvidia
  #   - rapidsai
  #   - numba
  #   - conda-forge
  #   - defaults
  build:
    - python
    - cython>=0.29,<0.30
    - setuptools
    - libcudf 0.4.0.*
    - libcudf_cffi 0.4.0.*
    - numba>=0.40
    - nvstrings
  run:
    - python
    - cython>=0.29,<0.30
    - setuptools
    - libcudf 0.4.0.*
    - libcudf_cffi 0.4.0.*
    - pandas>=0.23.4
    - numba>=0.40
    - nvstrings

test:
  requires:
    - distributed >=1.22.1
    - pytest
  imports:
    - cudf

about:
  home: http://rapids.ai/
  license: Apache-2.0
  # license_file: LICENSE
  summary: cuDF GPU DataFrame core library
