# Copyright (c) 2018-2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: cudf
  version: ${{ version }}

source:
  path: ../../..

build:
  string: cuda${{ cuda_major }}_py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh cudf
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    env:
      CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
      CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
      CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
      CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
      SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
      SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
      SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
      SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
      SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
      SCCACHE_S3_KEY_PREFIX: cudf-${{ env.get("RAPIDS_CONDA_ARCH") }}

requirements:
  build:
    - cmake ${{ cmake_version }}
    - ninja
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("cuda") }}
    - cuda-version =${{ cuda_version }}
    - ${{ stdlib("c") }}
  host:
    - python =${{ py_version }}
    - pip
    - cython >=3.0.3
    - rapids-build-backend >=0.4.0,<0.5.0.dev0
    - scikit-build-core >=0.10.0
    - dlpack >=0.8,<1.0
    - numba-cuda >=0.14.0,<0.15.0a0
    - libcudf =${{ version }}
    - pylibcudf =${{ version }}
    - rmm =${{ minor_version }}
    - cuda-cudart-dev
    - cuda-nvrtc
    - if: linux and x86_64
      then:
        - libcufile-dev
    - cuda-version =${{ cuda_version }}
  run:
    - python
    - typing_extensions >=4.0.0
    - pandas >=2.0,<2.4.0dev0
    - cupy >=12.0.0
    - numba-cuda >=0.14.0,<0.15.0a0
    - numba >=0.59.1,<0.62.0a0
    - numpy >=1.23,<3.0a0
    - pyarrow>=14.0.0,<20.0.0a0
    - libcudf =${{ version }}
    - pylibcudf =${{ version }}
    - ${{ pin_compatible("rmm", upper_bound="x.x") }}
    - fsspec >=0.6.0
    - cuda-cudart
    # Needed by Numba for CUDA support
    - cuda-nvcc-impl
    # TODO: Add nvjitlink here
    # xref: https://github.com/rapidsai/cudf/issues/12822
    - cuda-nvrtc
    - cuda-python >=12.6.2,<13.0a0
    - pynvjitlink
    - if: linux and x86_64
      then:
        - libcufile
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - nvtx >=0.2.1
    - packaging
    - cachetools
    - rich
  ignore_run_exports:
    from_package:
      - cuda-cudart-dev
      - if: linux and x86_64
        then: libcufile-dev
    by_name:
      - cuda-version

tests:
  - python:
      imports:
        - cudf
      pip_check: false
  - script:
      - python -c "import cudf; print(cudf.__version__)"
      - python -m cudf.pandas -c "import pandas as pd; print(pd)"
      - python -m cudf.pandas -c "import pandas as pd; print(pd.Series([1, 2, 3]))"
      - RAPIDS_NO_INITIALIZE=1 python -m cudf.pandas -c "import pandas as pd; print(pd.Series([1, 2, 3]))"
      - CUDF_NO_INITIALIZE=1 python -m cudf.pandas -c "import pandas as pd; print(pd.Series([1, 2, 3]))"

about:
  homepage: ${{ load_from_file("python/cudf/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cudf/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/cudf/pyproject.toml").project.description }}
