# SPDX-FileCopyrightText: Copyright (c) 2018-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: cudf-polars
  version: ${{ version }}

source:
  path: ../../..

build:
  noarch: python
  string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh cudf_polars

requirements:
  host:
    - python >=3.11
    - pip
    - rapids-build-backend >=0.4.0,<0.5.0
    - setuptools>=77.0.0
    - cuda-version =${{ cuda_version }}
  run:
    # 'nvidia-ml-py' provides the 'pynvml' module
    - nvidia-ml-py>=12
    - python
    - pylibcudf =${{ version }}
    - polars>=1.30,<1.36
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
  ignore_run_exports:
    by_name:
      - cuda-version

tests:
  - python:
      imports:
        - cudf_polars
      pip_check: false
  - script:
      - python -c "import cudf_polars; print(cudf_polars.__version__)"
      - RAPIDS_NO_INITIALIZE=1 python -c "import cudf_polars; print(cudf_polars.__version__)"
      - CUDF_NO_INITIALIZE=1 python -c "import cudf_polars; print(cudf_polars.__version__)"
      - RAPIDS_NO_INITIALIZE=1 python -c "import cudf_polars; import polars as pl; print(pl.Series([1, 2, 3]))"

about:
  homepage: ${{ load_from_file("python/cudf_polars/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cudf_polars/pyproject.toml").project.license }}
  summary: ${{ load_from_file("python/cudf_polars/pyproject.toml").project.description }}
