# SPDX-FileCopyrightText: Copyright (c) 2018-2025, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: cudf-polars
  version: ${{ version }}

source:
  path: ../../..

build:
  string: cuda${{ cuda_major }}_py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh cudf_polars
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    env:
      CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
      CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
      CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
      CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
      SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
      SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
      SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
      SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
      SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
      SCCACHE_S3_KEY_PREFIX: cudf-polars-${{ env.get("RAPIDS_CONDA_ARCH") }}

requirements:
  host:
    - python =${{ py_version }}
    - pip
    - rapids-build-backend >=0.4.0,<0.5.0.dev0
    - setuptools
    - cuda-version =${{ cuda_version }}
  run:
    # 'nvidia-ml-py' provides the 'pynvml' module
    - nvidia-ml-py>=12
    - python
    - pylibcudf =${{ version }}
    - polars >=1.29,<1.34
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - if: python == "3.10"
      then: typing_extensions
  ignore_run_exports:
    by_name:
      - cuda-version

tests:
  - python:
      imports:
        - cudf_polars
      pip_check: false
  - script:
      - python -c "import cudf_polars; print(cudf_polars.__version__)"
      - RAPIDS_NO_INITIALIZE=1 python -c "import cudf_polars; print(cudf_polars.__version__)"
      - CUDF_NO_INITIALIZE=1 python -c "import cudf_polars; print(cudf_polars.__version__)"
      - RAPIDS_NO_INITIALIZE=1 python -c "import cudf_polars; import polars as pl; print(pl.Series([1, 2, 3]))"

about:
  homepage: ${{ load_from_file("python/cudf_polars/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cudf_polars/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/cudf_polars/pyproject.toml").project.description }}
