#!/usr/bin/env bash

#
# SPDX-FileCopyrightText: Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

# This script generates the build info.
# Arguments:
#   version - The current version of cudf java code

echo_build_properties() {
  echo version="$1"
  echo user="$USER"
  echo revision="$(git rev-parse HEAD)"
  echo branch="$(git rev-parse --abbrev-ref HEAD)"
  echo date="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}

echo_build_properties "$1"
