# Copyright (c) 2018-2023, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version = environ['CONDA_PY'] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: custreamz
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=custreamz-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=custreamz-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS

requirements:
  host:
    - python
    - python-confluent-kafka >=1.9.0,<1.10.0a0
    - cudf_kafka ={{ version }}
    - cuda-version ={{ cuda_version }}
  run:
    - python
    - streamz
    - cudf ={{ version }}
    - cudf_kafka ={{ version }}
    - dask >=2023.5.1
    - dask-core >=2023.5.1
    - distributed >=2023.5.1
    - python-confluent-kafka >=1.9.0,<1.10.0a0
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}

test:
  requires:
    {% if cuda_major == "11" %}
    - cudatoolkit ={{ cuda_version }}
    {% endif %}
    - cuda-version ={{ cuda_version }}
  imports:
    - custreamz

about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: cuStreamz library
