# Copyright (c) 2018-2023, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version = environ['CONDA_PY'] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: custreamz
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PARALLEL_LEVEL
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=custreamz-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=custreamz-linux64 # [linux64]
    - SCCACHE_BUCKET
    - SCCACHE_REGION
    - SCCACHE_IDLE_TIMEOUT
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY

requirements:
  host:
    - python
    - python-confluent-kafka >=1.7.0,<1.8.0a0
    - cudf_kafka ={{ version }}
  run:
    - python
    - streamz
    - cudf ={{ version }}
    - dask >=2022.12.0
    - distributed >=2022.12.0
    - python-confluent-kafka >=1.7.0,<1.8.0a0
    - cudf_kafka ={{ version }}

test:
  requires:
    - cudatoolkit ={{ cuda_version }}
  imports:
    - custreamz

about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: cuStreamz library
