# SPDX-FileCopyrightText: Copyright (c) 2018-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: custreamz
  version: ${{ version }}

source:
  path: ../../..

build:
  noarch: python
  string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh custreamz

requirements:
  host:
    - python >=3.11
    - pip
    - rapids-build-backend >=0.4.0,<0.5.0
    - setuptools>=77.0.0
    - python-confluent-kafka >=2.8.0,<2.9.0
    - cudf_kafka =${{ version }}
    - cuda-version =${{ cuda_version }}
  run:
    - python
    - streamz
    - cudf =${{ version }}
    - cudf_kafka =${{ version }}
    - rapids-dask-dependency =${{ minor_version }}
    - python-confluent-kafka >=2.8.0,<2.9.0
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}

tests:
  - python:
      imports:
        - custreamz
      pip_check: false

about:
  homepage: ${{ load_from_file("python/custreamz/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/custreamz/pyproject.toml").project.license }}
  summary: ${{ load_from_file("python/custreamz/pyproject.toml").project.description }}
