# Copyright (c) 2018-2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: ${{ git.head_rev(".")[:8] }}

package:
  name: custreamz
  version: ${{ version }}

source:
  path: ../../..

build:
  string: cuda${{ cuda_major }}_py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh custreamz

requirements:
  host:
    - python =${{ py_version }}
    - pip
    - rapids-build-backend >=0.3.0,<0.4.0.dev0
    - setuptools
    - python-confluent-kafka >=2.5.0,<2.6.0a0
    - cudf_kafka =${{ version }}
    - cuda-version =${{ cuda_version }}
  run:
    - python
    - streamz
    - cudf =${{ version }}
    - cudf_kafka =${{ version }}
    - rapids-dask-dependency =${{ minor_version }}
    - python-confluent-kafka >=2.5.0,<2.6.0a0
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}

tests:
  - python:
      imports:
        - custreamz
      pip_check: false

about:
  homepage: ${{ load_from_file("python/custreamz/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/custreamz/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/custreamz/pyproject.toml").project.description }}
