# Copyright (c) 2020-2022, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ.get('CUDA', '11.5').split('.')[:2]) %}
{% set py_version = environ.get('python', '3.8') %}

package:
  name: cudf_kafka
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version.replace('.', '') }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX

requirements:
  build:
    - cmake >=3.20.1
  host:
    - python {{ py_version }}
    - cython >=0.29,<0.30
    - cudf {{ version }}
    - libcudf_kafka {{ version }}
    - setuptools
  run:
    - python {{ py_version }}
    - libcudf_kafka {{ version }}
    - python-confluent-kafka >=1.7.0,<1.8.0a0=py{{ py_version.replace('.', '') }}*
    - cudf {{ version }}

test:                                   # [linux64]
  requires:                             # [linux64]
    - cudatoolkit {{ cuda_version }}.*  # [linux64]
  imports:                              # [linux64]
    - cudf_kafka                        # [linux64]

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: libcudf_kafka library
