/*
 * Copyright (c) 2019-2024, NVIDIA CORPORATION.
 *
 * Copyright 2018-2019 BlazingDB, Inc.
 *     Copyright 2018 Christian Noboa Mardini <christian@blazingdb.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "assert_unary.h"

#include <cudf_test/base_fixture.hpp>
#include <cudf_test/column_wrapper.hpp>
#include <cudf_test/random.hpp>

#include <cudf/detail/iterator.cuh>
#include <cudf/transform.hpp>

namespace transformation {
struct UnaryOperationIntegrationTest : public cudf::test::BaseFixture {};

template <class dtype, class Op, class Data>
void test_udf(char const* udf, Op op, Data data_init, cudf::size_type size, bool is_ptx)
{
  auto all_valid = cudf::detail::make_counting_transform_iterator(0, [](auto i) { return true; });
  auto data_iter = cudf::detail::make_counting_transform_iterator(0, data_init);

  cudf::test::fixed_width_column_wrapper<dtype, typename decltype(data_iter)::value_type> in(
    data_iter, data_iter + size, all_valid);

  std::vector<cudf::column_view> inputs{in};

  std::unique_ptr<cudf::column> out =
    cudf::transform(inputs, udf, cudf::data_type(cudf::type_to_id<dtype>()), is_ptx);

  ASSERT_UNARY<dtype, dtype>(out->view(), in, op);
}

TEST_F(UnaryOperationIntegrationTest, Transform_FP32_FP32)
{
  // c = a*a*a*a
  std::string const cuda =
    R"***(
__device__ inline void    fdsf   (
       cudf::size_type i,
       float* out,
       float * in
)
{
float const a = in[i];
out[i] = a*a*a*a;
}
)***";

  std::string const ptx =
    R"***(
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-34841621
// Cuda compilation tools, release 12.6, V12.6.77
// Based on NVVM 7.0.1
//

.version 8.5
.target sm_70
.address_size 64

.func _Z5fdsf2iPfS_(
        .param .b64 _Z5fdsf2iPfS__param_0,
        .param .b32 _Z5fdsf2iPfS__param_1
)
{
        .reg .f32       %f<5>;
        .reg .b64       %rd<3>;


        ld.param.u64    %rd1, [_Z5fdsf2iPfS__param_0];
        ld.param.f32    %f1, [_Z5fdsf2iPfS__param_1];
        cvta.to.global.u64      %rd2, %rd1;
        mul.f32         %f2, %f1, %f1;
        mul.f32         %f3, %f2, %f1;
        mul.f32         %f4, %f3, %f1;
        st.global.f32   [%rd2], %f4;
        ret;

}
)***";

  using dtype    = float;
  auto op        = [](dtype a) { return a * a * a * a; };
  auto data_init = [](cudf::size_type row) { return row % 3; };

  test_udf<dtype>(cuda.c_str(), op, data_init, 500, false);
  test_udf<dtype>(ptx.c_str(), op, data_init, 500, true);
}

TEST_F(UnaryOperationIntegrationTest, Transform_INT32_INT32)
{
  // c = a * a - a
  std::string const cuda =
    R"***(
    __device__ inline void f(cudf::size_type i, int* output ,int * input)
    {
    output[i] = input[i] * input[i] - input[i];
    }
    )***";

  std::string const ptx =
    R"***(
.func _Z2ffiPiS_(
        .param .b64 _Z2ffiPiS__param_0,
        .param .b32 _Z2ffiPiS__param_1
)
{
        .reg .b32       %r<4>;
        .reg .b64       %rd<3>;


        ld.param.u64    %rd1, [_Z2ffiPiS__param_0];
        ld.param.u32    %r1, [_Z2ffiPiS__param_1];
        cvta.to.global.u64      %rd2, %rd1;
        mul.lo.s32      %r2, %r1, %r1;
        sub.s32         %r3, %r2, %r1;
        st.global.u32   [%rd2], %r3;
        ret;

}
)***";

  using dtype    = int;
  auto op        = [](dtype a) { return a * a - a; };
  auto data_init = [](cudf::size_type row) { return row % 78; };

  test_udf<dtype>(cuda.c_str(), op, data_init, 500, false);
  test_udf<dtype>(ptx.c_str(), op, data_init, 500, true);
}

TEST_F(UnaryOperationIntegrationTest, Transform_INT8_INT8)
{
  // Capitalize all the lower case letters
  // Assuming ASCII, the PTX code is compiled from the following CUDA code

  std::string const cuda =
    R"***(
__device__ inline void f(
  cudf::size_type i,
  signed char* output,
  signed char * input
){
  signed char in = input[i];

	if(in > 96 && in < 123){
  	output[i] = in - 32;
  }else{
  	output[i] = in;
  }
}
)***";

  std::string const ptx =
    R"***(
.func _Z2f3iPaS_(
        .param .b64 _Z2f3iPaS__param_0,
        .param .b32 _Z2f3iPaS__param_1
)
{
        .reg .pred      %p<2>;
        .reg .b16       %rs<6>;
        .reg .b64       %rd<3>;


        ld.param.u8     %rs1, [_Z2f3iPaS__param_1];
        ld.param.u64    %rd1, [_Z2f3iPaS__param_0];
        cvta.to.global.u64      %rd2, %rd1;
        add.s16         %rs2, %rs1, -97;
        and.b16         %rs3, %rs2, 255;
        setp.lt.u16     %p1, %rs3, 26;
        add.s16         %rs4, %rs1, -32;
        selp.b16        %rs5, %rs4, %rs1, %p1;
        st.global.u8    [%rd2], %rs5;
        ret;

}
)***";

  using dtype    = int8_t;
  auto op        = [](dtype a) { return std::toupper(a); };
  auto data_init = [](cudf::size_type row) { return 'a' + (row % 26); };

  test_udf<dtype>(cuda.c_str(), op, data_init, 500, false);
  test_udf<dtype>(ptx.c_str(), op, data_init, 500, true);
}

TEST_F(UnaryOperationIntegrationTest, Transform_Datetime)
{
  // Add one day to timestamp in microseconds

  std::string const cuda =
    R"***(
__device__ inline void f(cudf::size_type i, cudf::timestamp_us* output, cudf::timestamp_us * input)
{
  using dur = cuda::std::chrono::duration<int32_t, cuda::std::ratio<86400>>;
  output[i] = static_cast<cudf::timestamp_us>(input[i] + dur{1});
}

)***";

  using dtype = cudf::timestamp_us;
  auto op     = [](dtype a) {
    using dur = cuda::std::chrono::duration<int32_t, cuda::std::ratio<86400>>;
    return static_cast<cudf::timestamp_us>(a + dur{1});
  };
  auto random_eng = cudf::test::UniformRandomGenerator<cudf::timestamp_us::rep>(0, 100000000);
  auto data_init  = [&random_eng](cudf::size_type row) { return random_eng.generate(); };

  test_udf<dtype>(cuda.c_str(), op, data_init, 500, false);
}

}  // namespace transformation
