repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format (cuDF style)
        entry: clang-format --dry-run --Werror
        language: system
        files: '\.(c|cc|cpp|cxx|cu|h|hh|hpp|hxx|cuh)$'
