# Copyright (c) 2018-2022, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version = environ['CONDA_PY'] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}

package:
  name: dask-cudf
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda_{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PARALLEL_LEVEL
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=dask-cudf-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=dask-cudf-linux64 # [linux64]
    - SCCACHE_BUCKET
    - SCCACHE_REGION
    - SCCACHE_IDLE_TIMEOUT
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY

requirements:
  host:
    - python
    - cudf ={{ version }}
    - dask >=2022.12.0
    - distributed >=2022.12.0
    - cudatoolkit ={{ cuda_version }}
  run:
    - python
    - cudf ={{ version }}
    - dask >=2022.12.0
    - distributed >=2022.12.0
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}

test:
  requires:
    - cudatoolkit ={{ cuda_version }}
  imports:
    - dask_cudf


about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: dask-cudf library
