# SPDX-FileCopyrightText: Copyright (c) 2018-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: dask-cudf
  version: ${{ version }}

source:
  path: ../../..

build:
  noarch: python
  string: ${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh dask_cudf

requirements:
  host:
    - python >=3.11
    - pip
    - rapids-build-backend >=0.4.0,<0.5.0
    - setuptools>=77.0.0
  run:
    - python
    - cudf =${{ version }}
    # 'nvidia-ml-py' provides the 'pynvml' module
    - nvidia-ml-py>=12
    - rapids-dask-dependency =${{ minor_version }}

tests:
  - python:
      imports:
        - dask_cudf
      pip_check: false

about:
  homepage: ${{ load_from_file("python/dask_cudf/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/dask_cudf/pyproject.toml").project.license }}
  summary: ${{ load_from_file("python/dask_cudf/pyproject.toml").project.description }}
