# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
# Copyright (c) 2018-2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") | version_to_buildstring }}
  head_rev: ${{ git.head_rev(".")[:8] }}

package:
  name: dask-cudf
  version: ${{ version }}

source:
  path: ../../..

build:
  string: cuda${{ cuda_major }}_py${{ py_version }}_${{ date_string }}_${{ head_rev }}
  script:
    content:
      - ./build.sh dask_cudf
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    env:
      CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
      CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
      CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
      CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
      SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
      SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
      SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
      SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
      SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
      SCCACHE_S3_KEY_PREFIX: dask-cudf-${{ env.get("RAPIDS_CONDA_ARCH") }}

requirements:
  host:
    - python
    - rapids-build-backend >=0.3.0,<0.4.0.dev0
    - setuptools
    - cuda-version =${{ cuda_version }}
  run:
    - python
    - cudf =${{ version }}
    - pynvml >=12.0.0,<13.0.0a0
    - rapids-dask-dependency =${{ minor_version }}
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
  ignore_run_exports:
    by_name:
      - cuda-version

tests:
  - python:
      imports:
        - dask_cudf
      pip_check: false

about:
  homepage: ${{ load_from_file("python/dask_cudf/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/dask_cudf/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/dask_cudf/pyproject.toml").project.description }}
