# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

from collections.abc import Mapping
from typing import Any

class gpumemoryview:
    def __init__(self, data: Any): ...
    @property
    def __cuda_array_interface__(self) -> Mapping[str, Any]: ...
    def __len__(self) -> int: ...
    @property
    def ptr(self) -> int: ...
    @property
    def obj(self) -> Any: ...
    @property
    def cai(self) -> dict[str, Any]: ...
    @property
    def nbytes(self) -> int: ...
