# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

def enable() -> None: ...
def disable() -> None: ...
def enable_debugging() -> None: ...
def disable_debugging() -> None: ...
