# Copyright (c) 2018-2021, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', '10.1').split('.')[:2]) %}

package:
  name: libcudf
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
    - PROJECT_FLASH
    - CCACHE_DIR
    - CCACHE_NOHASHDIR
    - CCACHE_COMPILERCHECK
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
  run_exports:
    - {{ pin_subpackage("libcudf", max_pin="x.x") }}

requirements:
  build:
    - cmake >=3.20.1
  host:
    - librmm {{ minor_version }}.*
    - cudatoolkit {{ cuda_version }}.*
    - arrow-cpp 4.0.1 *cuda
    - arrow-cpp-proc * cuda
    - dlpack>=0.5,<0.6.0a0
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - arrow-cpp * *cuda
    - arrow-cpp-proc * cuda
    - {{ pin_compatible('dlpack', max_pin='x.x') }}

test:
  commands:
    - test -f $PREFIX/lib/libcudf.so
    - test -f $PREFIX/lib/libcudftestutil.a
    - test -f $PREFIX/include/cudf/aggregation.hpp
    - test -f $PREFIX/include/cudf/ast/transform.hpp
    - test -f $PREFIX/include/cudf/ast/detail/linearizer.hpp
    - test -f $PREFIX/include/cudf/ast/detail/operators.hpp
    - test -f $PREFIX/include/cudf/ast/nodes.hpp
    - test -f $PREFIX/include/cudf/ast/operators.hpp
    - test -f $PREFIX/include/cudf/binaryop.hpp
    - test -f $PREFIX/include/cudf/labeling/label_bins.hpp
    - test -f $PREFIX/include/cudf/column/column_factories.hpp
    - test -f $PREFIX/include/cudf/column/column.hpp
    - test -f $PREFIX/include/cudf/column/column_view.hpp
    - test -f $PREFIX/include/cudf/concatenate.hpp
    - test -f $PREFIX/include/cudf/copying.hpp
    - test -f $PREFIX/include/cudf/datetime.hpp
    - test -f $PREFIX/include/cudf/detail/aggregation/aggregation.hpp
    - test -f $PREFIX/include/cudf/detail/aggregation/result_cache.hpp
    - test -f $PREFIX/include/cudf/detail/label_bins.hpp
    - test -f $PREFIX/include/cudf/detail/binaryop.hpp
    - test -f $PREFIX/include/cudf/detail/concatenate.hpp
    - test -f $PREFIX/include/cudf/detail/copy.hpp
    - test -f $PREFIX/include/cudf/detail/datetime.hpp
    - test -f $PREFIX/include/cudf/detail/fill.hpp
    - test -f $PREFIX/include/cudf/detail/gather.hpp
    - test -f $PREFIX/include/cudf/detail/groupby.hpp
    - test -f $PREFIX/include/cudf/detail/groupby/sort_helper.hpp
    - test -f $PREFIX/include/cudf/detail/groupby/group_replace_nulls.hpp
    - test -f $PREFIX/include/cudf/detail/hashing.hpp
    - test -f $PREFIX/include/cudf/detail/interop.hpp
    - test -f $PREFIX/include/cudf/detail/is_element_valid.hpp
    - test -f $PREFIX/include/cudf/detail/null_mask.hpp
    - test -f $PREFIX/include/cudf/detail/nvtx/nvtx3.hpp
    - test -f $PREFIX/include/cudf/detail/nvtx/ranges.hpp
    - test -f $PREFIX/include/cudf/detail/quantiles.hpp
    - test -f $PREFIX/include/cudf/detail/reduction_functions.hpp
    - test -f $PREFIX/include/cudf/detail/repeat.hpp
    - test -f $PREFIX/include/cudf/detail/replace.hpp
    - test -f $PREFIX/include/cudf/detail/reshape.hpp
    - test -f $PREFIX/include/cudf/detail/rolling.hpp
    - test -f $PREFIX/include/cudf/detail/round.hpp
    - test -f $PREFIX/include/cudf/detail/scan.hpp
    - test -f $PREFIX/include/cudf/detail/scatter.hpp
    - test -f $PREFIX/include/cudf/detail/search.hpp
    - test -f $PREFIX/include/cudf/detail/sequence.hpp
    - test -f $PREFIX/include/cudf/detail/sorting.hpp
    - test -f $PREFIX/include/cudf/detail/stream_compaction.hpp
    - test -f $PREFIX/include/cudf/detail/transform.hpp
    - test -f $PREFIX/include/cudf/detail/transpose.hpp
    - test -f $PREFIX/include/cudf/detail/unary.hpp
    - test -f $PREFIX/include/cudf/detail/utilities/alignment.hpp
    - test -f $PREFIX/include/cudf/detail/utilities/integer_utils.hpp
    - test -f $PREFIX/include/cudf/detail/utilities/int_fastdiv.h
    - test -f $PREFIX/include/cudf/detail/utilities/vector_factories.hpp
    - test -f $PREFIX/include/cudf/dictionary/detail/concatenate.hpp
    - test -f $PREFIX/include/cudf/dictionary/detail/encode.hpp
    - test -f $PREFIX/include/cudf/dictionary/detail/merge.hpp
    - test -f $PREFIX/include/cudf/dictionary/detail/replace.hpp
    - test -f $PREFIX/include/cudf/dictionary/detail/search.hpp
    - test -f $PREFIX/include/cudf/dictionary/detail/update_keys.hpp
    - test -f $PREFIX/include/cudf/dictionary/dictionary_column_view.hpp
    - test -f $PREFIX/include/cudf/dictionary/dictionary_factories.hpp
    - test -f $PREFIX/include/cudf/dictionary/encode.hpp
    - test -f $PREFIX/include/cudf/dictionary/search.hpp
    - test -f $PREFIX/include/cudf/dictionary/update_keys.hpp
    - test -f $PREFIX/include/cudf/filling.hpp
    - test -f $PREFIX/include/cudf/fixed_point/fixed_point.hpp
    - test -f $PREFIX/include/cudf/groupby.hpp
    - test -f $PREFIX/include/cudf/hashing.hpp
    - test -f $PREFIX/include/cudf/interop.hpp
    - test -f $PREFIX/include/cudf/io/avro.hpp
    - test -f $PREFIX/include/cudf/io/data_sink.hpp
    - test -f $PREFIX/include/cudf/io/datasource.hpp
    - test -f $PREFIX/include/cudf/io/orc_metadata.hpp
    - test -f $PREFIX/include/cudf/io/csv.hpp
    - test -f $PREFIX/include/cudf/io/detail/avro.hpp
    - test -f $PREFIX/include/cudf/io/detail/csv.hpp
    - test -f $PREFIX/include/cudf/io/detail/json.hpp
    - test -f $PREFIX/include/cudf/io/detail/orc.hpp
    - test -f $PREFIX/include/cudf/io/detail/parquet.hpp
    - test -f $PREFIX/include/cudf/io/detail/utils.hpp
    - test -f $PREFIX/include/cudf/io/json.hpp
    - test -f $PREFIX/include/cudf/io/orc.hpp
    - test -f $PREFIX/include/cudf/io/parquet.hpp
    - test -f $PREFIX/include/cudf/io/types.hpp
    - test -f $PREFIX/include/cudf/ipc.hpp
    - test -f $PREFIX/include/cudf/join.hpp
    - test -f $PREFIX/include/cudf/lists/detail/combine.hpp
    - test -f $PREFIX/include/cudf/lists/detail/concatenate.hpp
    - test -f $PREFIX/include/cudf/lists/detail/copying.hpp
    - test -f $PREFIX/include/cudf/lists/lists_column_factories.hpp
    - test -f $PREFIX/include/cudf/lists/detail/drop_list_duplicates.hpp
    - test -f $PREFIX/include/cudf/lists/detail/interleave_columns.hpp
    - test -f $PREFIX/include/cudf/lists/detail/sorting.hpp
    - test -f $PREFIX/include/cudf/lists/detail/scatter_helper.cuh
    - test -f $PREFIX/include/cudf/lists/combine.hpp
    - test -f $PREFIX/include/cudf/lists/count_elements.hpp
    - test -f $PREFIX/include/cudf/lists/explode.hpp
    - test -f $PREFIX/include/cudf/lists/drop_list_duplicates.hpp
    - test -f $PREFIX/include/cudf/lists/extract.hpp
    - test -f $PREFIX/include/cudf/lists/contains.hpp
    - test -f $PREFIX/include/cudf/lists/gather.hpp
    - test -f $PREFIX/include/cudf/lists/lists_column_view.hpp
    - test -f $PREFIX/include/cudf/lists/sorting.hpp
    - test -f $PREFIX/include/cudf/merge.hpp
    - test -f $PREFIX/include/cudf/null_mask.hpp
    - test -f $PREFIX/include/cudf/partitioning.hpp
    - test -f $PREFIX/include/cudf/quantiles.hpp
    - test -f $PREFIX/include/cudf/reduction.hpp
    - test -f $PREFIX/include/cudf/replace.hpp
    - test -f $PREFIX/include/cudf/reshape.hpp
    - test -f $PREFIX/include/cudf/rolling.hpp
    - test -f $PREFIX/include/cudf/rolling/range_window_bounds.hpp
    - test -f $PREFIX/include/cudf/round.hpp
    - test -f $PREFIX/include/cudf/scalar/scalar_factories.hpp
    - test -f $PREFIX/include/cudf/scalar/scalar.hpp
    - test -f $PREFIX/include/cudf/search.hpp
    - test -f $PREFIX/include/cudf/sorting.hpp
    - test -f $PREFIX/include/cudf/stream_compaction.hpp
    - test -f $PREFIX/include/cudf/strings/attributes.hpp
    - test -f $PREFIX/include/cudf/strings/capitalize.hpp
    - test -f $PREFIX/include/cudf/strings/case.hpp
    - test -f $PREFIX/include/cudf/strings/char_types/char_cases.hpp
    - test -f $PREFIX/include/cudf/strings/char_types/char_types.hpp
    - test -f $PREFIX/include/cudf/strings/combine.hpp
    - test -f $PREFIX/include/cudf/strings/contains.hpp
    - test -f $PREFIX/include/cudf/strings/convert/convert_booleans.hpp
    - test -f $PREFIX/include/cudf/strings/convert/convert_datetime.hpp
    - test -f $PREFIX/include/cudf/strings/convert/convert_durations.hpp
    - test -f $PREFIX/include/cudf/strings/convert/convert_fixed_point.hpp
    - test -f $PREFIX/include/cudf/strings/convert/convert_floats.hpp
    - test -f $PREFIX/include/cudf/strings/convert/convert_integers.hpp
    - test -f $PREFIX/include/cudf/strings/convert/convert_ipv4.hpp
    - test -f $PREFIX/include/cudf/strings/convert/convert_urls.hpp
    - test -f $PREFIX/include/cudf/strings/detail/combine.hpp
    - test -f $PREFIX/include/cudf/strings/detail/concatenate.hpp
    - test -f $PREFIX/include/cudf/strings/detail/converters.hpp
    - test -f $PREFIX/include/cudf/strings/detail/copying.hpp
    - test -f $PREFIX/include/cudf/strings/detail/fill.hpp
    - test -f $PREFIX/include/cudf/strings/detail/json.hpp
    - test -f $PREFIX/include/cudf/strings/detail/replace.hpp
    - test -f $PREFIX/include/cudf/strings/detail/utilities.hpp
    - test -f $PREFIX/include/cudf/strings/extract.hpp
    - test -f $PREFIX/include/cudf/strings/findall.hpp
    - test -f $PREFIX/include/cudf/strings/find.hpp
    - test -f $PREFIX/include/cudf/strings/find_multiple.hpp
    - test -f $PREFIX/include/cudf/strings/json.hpp
    - test -f $PREFIX/include/cudf/strings/padding.hpp
    - test -f $PREFIX/include/cudf/strings/repeat_strings.hpp
    - test -f $PREFIX/include/cudf/strings/replace.hpp
    - test -f $PREFIX/include/cudf/strings/replace_re.hpp
    - test -f $PREFIX/include/cudf/strings/split/partition.hpp
    - test -f $PREFIX/include/cudf/strings/split/split.hpp
    - test -f $PREFIX/include/cudf/strings/string_view.hpp
    - test -f $PREFIX/include/cudf/strings/strings_column_view.hpp
    - test -f $PREFIX/include/cudf/strings/strip.hpp
    - test -f $PREFIX/include/cudf/strings/substring.hpp
    - test -f $PREFIX/include/cudf/strings/translate.hpp
    - test -f $PREFIX/include/cudf/strings/wrap.hpp
    - test -f $PREFIX/include/cudf/structs/structs_column_view.hpp
    - test -f $PREFIX/include/cudf/structs/struct_view.hpp
    - test -f $PREFIX/include/cudf/structs/detail/concatenate.hpp
    - test -f $PREFIX/include/cudf/table/table.hpp
    - test -f $PREFIX/include/cudf/table/table_view.hpp
    - test -f $PREFIX/include/cudf/transform.hpp
    - test -f $PREFIX/include/cudf/transpose.hpp
    - test -f $PREFIX/include/cudf/types.hpp
    - test -f $PREFIX/include/cudf/unary.hpp
    - test -f $PREFIX/include/cudf/utilities/bit.hpp
    - test -f $PREFIX/include/cudf/utilities/span.hpp
    - test -f $PREFIX/include/cudf/utilities/error.hpp
    - test -f $PREFIX/include/cudf/utilities/traits.hpp
    - test -f $PREFIX/include/cudf/utilities/type_dispatcher.hpp
    - test -f $PREFIX/include/cudf/utilities/type_checks.hpp
    - test -f $PREFIX/include/cudf/utilities/default_stream.hpp
    - test -f $PREFIX/include/cudf/wrappers/dictionary.hpp
    - test -f $PREFIX/include/cudf/wrappers/durations.hpp
    - test -f $PREFIX/include/cudf/wrappers/timestamps.hpp
    - test -f $PREFIX/include/cudf_test/detail/column_utilities.hpp
    - test -f $PREFIX/include/cudf_test/base_fixture.hpp
    - test -f $PREFIX/include/cudf_test/column_utilities.hpp
    - test -f $PREFIX/include/cudf_test/column_wrapper.hpp
    - test -f $PREFIX/include/cudf_test/cudf_gtest.hpp
    - test -f $PREFIX/include/cudf_test/cxxopts.hpp
    - test -f $PREFIX/include/cudf_test/file_utilities.hpp
    - test -f $PREFIX/include/cudf_test/iterator_utilities.hpp
    - test -f $PREFIX/include/cudf_test/table_utilities.hpp
    - test -f $PREFIX/include/cudf_test/timestamp_utilities.cuh
    - test -f $PREFIX/include/cudf_test/type_list_utilities.hpp
    - test -f $PREFIX/include/cudf_test/type_lists.hpp

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: libcudf library
