# Copyright (c) 2018, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}

package:
  name: libcudf
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ git_revision_count }}
  string: cuda{{ cuda_version }}_{{ git_revision_count }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
  run_exports:
    - {{ pin_subpackage("libcudf", max_pin="x.x") }}

requirements:
  build:
    - cmake >=3.12.4
  host:
    - librmm {{ minor_version }}.*
    - libnvstrings {{ minor_version }}.*
    - cudatoolkit {{ cuda_version }}.*
    - arrow-cpp 0.14.1.*
    - double-conversion
    - rapidjson
    - flatbuffers
    - boost-cpp
    - dlpack
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - arrow-cpp 0.14.1.*
    - dlpack

test:
  commands:
    - test -f $PREFIX/lib/libcudf.so
    - test -f $PREFIX/include/cudf/legacy/bitmask.hpp
    - test -f $PREFIX/include/cudf/legacy/column.hpp
    - test -f $PREFIX/include/cudf/legacy/table.hpp
    - test -f $PREFIX/include/cudf/utilities/legacy/nvcategory_util.hpp
    - test -f $PREFIX/include/cudf/utilities/legacy/type_dispatcher.hpp
    - test -f $PREFIX/include/cudf/utilities/legacy/wrapper_types.hpp
    - test -f $PREFIX/include/cudf/binaryop.hpp
    - test -f $PREFIX/include/cudf/convert_types.h
    - test -f $PREFIX/include/cudf/copying.hpp
    - test -f $PREFIX/include/cudf/cudf.h
    - test -f $PREFIX/include/cudf/datetime.hpp
    - test -f $PREFIX/include/cudf/filling.hpp
    - test -f $PREFIX/include/cudf/functions.h
    - test -f $PREFIX/include/cudf/gis.hpp
    - test -f $PREFIX/include/cudf/groupby.hpp
    - test -f $PREFIX/include/cudf/io_functions.h
    - test -f $PREFIX/include/cudf/io_functions.hpp
    - test -f $PREFIX/include/cudf/io_readers.hpp
    - test -f $PREFIX/include/cudf/io_types.h
    - test -f $PREFIX/include/cudf/io_types.hpp
    - test -f $PREFIX/include/cudf/ipc.hpp
    - test -f $PREFIX/include/cudf/merge.hpp
    - test -f $PREFIX/include/cudf/predicates.hpp
    - test -f $PREFIX/include/cudf/reduction.hpp
    - test -f $PREFIX/include/cudf/replace.hpp
    - test -f $PREFIX/include/cudf/rolling.hpp
    - test -f $PREFIX/include/cudf/search.hpp
    - test -f $PREFIX/include/cudf/stream_compaction.hpp
    - test -f $PREFIX/include/cudf/transform.hpp
    - test -f $PREFIX/include/cudf/types.h
    - test -f $PREFIX/include/cudf/types.hpp
    - test -f $PREFIX/include/cudf/unary.hpp

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: libcudf library
