/*
 * Copyright (c) 2021, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#pragma once

#include <cudf/column/column.hpp>
#include <cudf/lists/lists_column_view.hpp>

namespace cudf {
namespace lists {
/**
 * @addtogroup lists_combine
 * @{
 * @file
 */

/*
 * @brief Flag to specify whether a null list element will be ignored from concatenation, or the
 * entire concatenation result involving null list elements will be a null element.
 */
enum class concatenate_null_policy { IGNORE, NULLIFY_OUTPUT_ROW };

/**
 * @brief Row-wise concatenating multiple lists columns into a single lists column.
 *
 * The output column is generated by concatenating the elements within each row of the input
 * table. If any row of the input table contains null elements, the concatenation process will
 * either ignore those null elements, or will simply set the entire resulting row to be a null
 * element.
 *
 * @code{.pseudo}
 * s1 = [{0, 1}, {2, 3, 4}, {5}, {}, {6, 7}]
 * s2 = [{8}, {9}, {}, {10, 11, 12}, {13, 14, 15, 16}]
 * r = lists::concatenate_rows(s1, s2)
 * r is now [{0, 1, 8}, {2, 3, 4, 9}, {5}, {10, 11, 12}, {6, 7, 13, 14, 15, 16}]
 * @endcode
 *
 * @throws cudf::logic_error if any column of the input table is not a lists columns.
 * @throws cudf::logic_error if any lists column contains nested typed entry.
 * @throws cudf::logic_error if all lists columns do not have the same entry type.
 *
 * @param input Table of lists to be concatenated.
 * @param null_policy The parameter to specify whether a null list element will be ignored from
 *        concatenation, or any concatenation involving a null element will result in a null list.
 * @param mr Device memory resource used to allocate the returned column's device memory.
 * @return A new column in which each row is a list resulted from concatenating all list elements in
 *         the corresponding row of the input table.
 */
std::unique_ptr<column> concatenate_rows(
  table_view const& input,
  concatenate_null_policy null_policy = concatenate_null_policy::IGNORE,
  rmm::mr::device_memory_resource* mr = rmm::mr::get_current_device_resource());

/**
 * @brief Concatenating multiple lists corresponding to the same key value into a single list.
 *
 * Given a keys column and a lists column where each row in the lists column corresponds to a
 * key at the same row in the keys column, an output lists column is generated by concatenating
 * the list elements having the same key. If the input lists column contains null list elements,
 * the concatenation process will either ignore those null elements, or will simply set the entire
 * resulting row to be a null element.
 *
 * The input keys column is also filtered out to generate an output keys column that contains
 * only unique keys. Each row in the output lists column corresponds to a key in the same row of
 * this output keys column. By the current implementation, the output keys are sorted by ascending
 * order, with nulls come first.
 *
 * @code{.pseudo}
 * keys = ['A', 'B', 'A', 'C', 'A']
 * values = [{0, 1}, {2, 3, 4}, {5}, {}, {6, 7}]
 * [out_keys, out_values] = lists::concatenate_by_key(keys, values)
 * out_keys is ['A', 'B', 'C'], and out_values is [{0, 1, 5, 6, 7}, {2, 3, 4}, {}]
 * @endcode
 *
 * @throws cudf::logic_error if the second input column is not a lists columns.
 * @throws cudf::logic_error if the input lists column contains nested typed entry.
 * @throws cudf::logic_error if the keys and values columns have different sizes.
 *
 * @param keys The column containing keys (which may be nullable).
 * @param lists_column The lists column containing list elements to concatenate.
 * @param null_policy The parameter to specify whether a null list element will be ignored from
 *        concatenation, or any concatenation involving a null element will result in a null list.
 * @param mr Device memory resource used to allocate the returned column's device memory.
 * @return A pair of columns containing unique keys and the resulting lists, in which each row is
 *         a list concatenated from the input list elements corresponding to the same key.
 */
std::pair<std::unique_ptr<column>, std::unique_ptr<column>> concatenate_by_key(
  column_view const& keys,
  column_view const& lists_column,
  concatenate_null_policy null_policy = concatenate_null_policy::IGNORE,
  rmm::mr::device_memory_resource* mr = rmm::mr::get_current_device_resource());

/** @} */  // end of group
}  // namespace lists
}  // namespace cudf
