/*
 * Copyright (c) 2021, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#pragma once

#include <cudf/column/column.hpp>
#include <cudf/lists/lists_column_view.hpp>
#include <cudf/stream_compaction.hpp>

namespace cudf {
namespace lists {
/**
 * @addtogroup lists_drop_duplicates
 * @{
 * @file
 */

/**
 * @brief Create new lists columns by copying entries from the input lists columns ignoring
 * duplicate list entries.
 *
 * Given a pair of keys-values lists columns. At each row, each list entry in one column maps
 * to a list entry in the other column by linear order and vice versa thus lists at each row
 * in both keys and values columns always have the same size. A pair of output keys and values lists
 * columns are generated by copying entries from the input lists columns. The duplicate entries in
 * each list of the keys column are ignored from copying to output only the unique list entries.
 * Entries in the values column mapped to these key entries are also copied or ignored along with
 * them.
 *
 * The users are responsible to have the keys-values lists columns having the same number of entries
 * at each row. Otherwise, crash may happen, or the results will be undefined.
 *
 * When copying unique key entries for the output, depending on the value of the @p keep_option
 * parameter:
 * - KEEP_FIRST: only copy the first key in the sequence of duplicate ones
 * - KEEP_LAST: only copy the last key in the sequence of duplicate ones
 * - KEEP_NONE: only copy the key entries that are not repeated
 *
 * In the current implementation, entries within each list in the output keys column are sorted by
 * ascending order (nulls last) using stable sort, but this is not guaranteed in future
 * implementation.
 *
 * @throw cudf::logic_error if the child column of the input keys column contains nested type other
 *        than STRUCT.
 * @throw cudf::logic_error if the input keys and values columns having different numbers of rows.
 *
 * @param keys The input keys lists column to check for uniqueness and copy unique entries.
 * @param values The values lists column in which the entries are mapped to entries in the key
 *        column.
 * @param nulls_equal Flag to specify whether null key entries should be considered equal.
 * @param nans_equal Flag to specify whether NaN key entries should be considered as equal value
 *        (only applicable for floating point keys entries).
 * @param keep_option Flag to specify which entries will be copied from the input to the output.
 * @param mr Device resource used to allocate memory.
 *
 * @code{.pseudo}
 * keys   = { {1,   1,   2,   3},   {4},   NULL, {}, {NULL, NULL, NULL, 5,   6,   6,   6,   5} }
 * values = { {"a", "b", "c", "d"}, {"e"}, NULL, {}, {"N0", "N1", "N2", "f", "g", "h", "i", "j"} }
 *
 * [out_keys, out_values] = drop_list_duplicates(keys, values, duplicate_keep_option::KEEP_FIRST)
 * out_keys   = { {1,   2,   3},   {4},   NULL, {}, {5,   6,   NULL} }
 * out_values = { {"a", "c", "d"}, {"e"}, NULL, {}, {"f", "g", "N0"} }
 *
 * [out_keys, out_values] = drop_list_duplicates(keys, values, duplicate_keep_option::KEEP_LAST)
 * out_keys   = { {1,   2,   3},   {4},   NULL, {}, {5,   6,   NULL} }
 * out_values = { {"b", "c", "d"}, {"e"}, NULL, {}, {"j", "i", "N2"} }
 *
 * [out_keys, out_values] = drop_list_duplicates(keys, values, duplicate_keep_option::KEEP_NONE)
 * out_keys   = { {2,   3},   {4},   NULL, {}, {} }
 * out_values = { {"c", "d"}, {"e"}, NULL, {}, {} }
 * @endcode
 *
 * @return A pair of lists columns storing the results from extracting unique key entries and their
 * corresponding values entries from the input.
 */
std::pair<std::unique_ptr<column>, std::unique_ptr<column>> drop_list_duplicates(
  lists_column_view const& keys,
  lists_column_view const& values,
  duplicate_keep_option keep_option   = duplicate_keep_option::KEEP_FIRST,
  null_equality nulls_equal           = null_equality::EQUAL,
  nan_equality nans_equal             = nan_equality::UNEQUAL,
  rmm::mr::device_memory_resource* mr = rmm::mr::get_current_device_resource());

/**
 * @brief Create a new list column by copying entries from the input lists column ignoring
 * duplicate list entries.
 *
 * Given a lists column, an output lists column is generated by copying entries from the input lists
 * column in a way such that the duplicate entries in each list are ignored from copying to output
 * only the unique list entries.
 *
 * In the current implementation, entries within each list in the output column are sorted by
 * ascending order (nulls last) using stable sort, but this is not guaranteed in future
 * implementation.
 *
 * @throw cudf::logic_error if the child column of the input lists column contains nested type other
 *        than STRUCT.
 *
 * @param input The input lists column to check and copy unique entries.
 * @param nulls_equal Flag to specify whether null key entries should be considered equal.
 * @param nans_equal Flag to specify whether NaN key entries should be considered as equal value
 *        (only applicable for floating point keys column).
 * @param keep_option Flag to specify which entries will be copied from the input to the output.
 * @param mr Device resource used to allocate memory.
 *
 * @code{.pseudo}
 * input  = { {1, 1, 2, 3}, {4}, NULL, {}, {NULL, NULL, NULL, 5, 6, 6, 6, 5} }
 * drop_list_duplicates(input) = { {1, 2, 3}, {4}, NULL, {}, {5, 6, NULL} }
 * @endcode
 *
 * @return A lists column storing the results from extracting unique list entries from the input.
 */
std::unique_ptr<column> drop_list_duplicates(
  lists_column_view const& input,
  null_equality nulls_equal           = null_equality::EQUAL,
  nan_equality nans_equal             = nan_equality::UNEQUAL,
  rmm::mr::device_memory_resource* mr = rmm::mr::get_current_device_resource());

/** @} */  // end of group
}  // namespace lists
}  // namespace cudf
