# Copyright (c) 2021-2022, NVIDIA CORPORATION.

[build-system]

requires = [
    "wheel",
    "setuptools",
    "cython>=0.29,<0.30",
    "scikit-build>=0.13.1",
    "cmake>=3.23.1,!=3.25.0",
    "ninja",
    "numpy",
    "pyarrow==9.0.0",
    "protoc-wheel",
    "versioneer",
]
build-backend = "backend"
backend-path = ["_custom_build"]
