/*
 * SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#include <jit/lite/lite.cuh>

namespace __attribute__((visibility("default"))) cudf
{
  namespace lite {

  // Pre-instantiate operator entry points so they can be linked by symbol name.

#define UNOP_R(NAME, RET_TYPE, TYPE)                                                            \
  extern "C" __device__ int NAME##__##TYPE(RET_TYPE* out, TYPE const* a)                        \
  {                                                                                             \
    return operators::NAME<TYPE>(out, a);                                                       \
  }                                                                                             \
                                                                                                \
  extern "C" __device__ int NAME##__opt##TYPE(optional<RET_TYPE>* out, optional<TYPE> const* a) \
  {                                                                                             \
    return operators::NAME<TYPE>(out, a);                                                       \
  }

#define UNOP(NAME, TYPE) UNOP_R(NAME, TYPE, TYPE)

#define UNPRED(NAME, TYPE) UNOP_R(NAME, bool, TYPE)

#define CASTOP(NAME, TARGET, TYPE) UNOP_R(NAME, TARGET, TYPE)

#define BINOP_R(NAME, RET_TYPE, TYPE)                                                   \
  extern "C" __device__ int NAME##__##TYPE(RET_TYPE* out, TYPE const* a, TYPE const* b) \
  {                                                                                     \
    return operators::NAME<TYPE>(out, a, b);                                            \
  }                                                                                     \
                                                                                        \
  extern "C" __device__ int NAME##__opt##TYPE(                                          \
    optional<RET_TYPE>* out, optional<TYPE> const* a, optional<TYPE> const* b)          \
  {                                                                                     \
    return operators::NAME<TYPE>(out, a, b);                                            \
  }

#define BINOP(NAME, TYPE) BINOP_R(NAME, TYPE, TYPE)

#define BINCMP(NAME, TYPE) BINOP_R(NAME, bool, TYPE)

#define COND_OP_R(NAME, RET_TYPE, TYPE)                                \
  extern "C" __device__ int NAME##__##TYPE(                            \
    RET_TYPE* out, bool const* a, TYPE const* b, TYPE const* c)        \
  {                                                                    \
    return operators::NAME<TYPE>(out, a, b, c);                        \
  }                                                                    \
                                                                       \
  extern "C" __device__ int NAME##__opt##TYPE(optional<RET_TYPE>* out, \
                                              optional<bool> const* a, \
                                              optional<TYPE> const* b, \
                                              optional<TYPE> const* c) \
  {                                                                    \
    return operators::NAME<TYPE>(out, a, b, c);                        \
  }

#define COND_OP(NAME, TYPE) COND_OP_R(NAME, TYPE, TYPE)

  // Unary numeric
  UNOP(abs, i8)
  UNOP(abs, i16)
  UNOP(abs, i32)
  UNOP(abs, i64)
  UNOP(abs, f32)
  UNOP(abs, f64)

  // Unary floating point math
  UNOP(arccos, f32)
  UNOP(arccos, f64)
  UNOP(arccosh, f32)
  UNOP(arccosh, f64)
  UNOP(arcsin, f32)
  UNOP(arcsin, f64)
  UNOP(arcsinh, f32)
  UNOP(arcsinh, f64)
  UNOP(arctan, f32)
  UNOP(arctan, f64)
  UNOP(arctanh, f32)
  UNOP(arctanh, f64)
  UNOP(cbrt, f32)
  UNOP(cbrt, f64)
  UNOP(ceil, f32)
  UNOP(ceil, f64)
  UNOP(cos, f32)
  UNOP(cos, f64)
  UNOP(cosh, f32)
  UNOP(cosh, f64)
  UNOP(exp, f32)
  UNOP(exp, f64)
  UNOP(floor, f32)
  UNOP(floor, f64)
  UNOP(log, f32)
  UNOP(log, f64)
  UNOP(rint, f32)
  UNOP(rint, f64)
  UNOP(sin, f32)
  UNOP(sin, f64)
  UNOP(sinh, f32)
  UNOP(sinh, f64)
  UNOP(tanh, f32)
  UNOP(tanh, f64)

  // Unary bitwise and identity-like
  UNOP(bit_invert, i8)
  UNOP(bit_invert, i16)
  UNOP(bit_invert, i32)
  UNOP(bit_invert, i64)
  UNOP(bit_invert, u8)
  UNOP(bit_invert, u16)
  UNOP(bit_invert, u32)
  UNOP(bit_invert, u64)

  UNOP(identity, b8)
  UNOP(identity, i8)
  UNOP(identity, i16)
  UNOP(identity, i32)
  UNOP(identity, i64)
  UNOP(identity, u8)
  UNOP(identity, u16)
  UNOP(identity, u32)
  UNOP(identity, u64)
  UNOP(identity, f32)
  UNOP(identity, f64)
  UNOP(identity, dec32)
  UNOP(identity, dec64)
  UNOP(identity, dec128)
  UNOP(identity, ts_D)
  UNOP(identity, ts_h)
  UNOP(identity, ts_m)
  UNOP(identity, ts_s)
  UNOP(identity, ts_ms)
  UNOP(identity, ts_us)
  UNOP(identity, ts_ns)
  UNOP(identity, dur_D)
  UNOP(identity, dur_h)
  UNOP(identity, dur_m)
  UNOP(identity, dur_s)
  UNOP(identity, dur_ms)
  UNOP(identity, dur_us)
  UNOP(identity, dur_ns)
  UNOP(identity, str)

  UNPRED(is_null, b8)
  UNPRED(is_null, i8)
  UNPRED(is_null, i16)
  UNPRED(is_null, i32)
  UNPRED(is_null, i64)
  UNPRED(is_null, u8)
  UNPRED(is_null, u16)
  UNPRED(is_null, u32)
  UNPRED(is_null, u64)
  UNPRED(is_null, f32)
  UNPRED(is_null, f64)
  UNPRED(is_null, dec32)
  UNPRED(is_null, dec64)
  UNPRED(is_null, dec128)
  UNPRED(is_null, ts_D)
  UNPRED(is_null, ts_h)
  UNPRED(is_null, ts_m)
  UNPRED(is_null, ts_s)
  UNPRED(is_null, ts_ms)
  UNPRED(is_null, ts_us)
  UNPRED(is_null, ts_ns)
  UNPRED(is_null, dur_D)
  UNPRED(is_null, dur_h)
  UNPRED(is_null, dur_m)
  UNPRED(is_null, dur_s)
  UNPRED(is_null, dur_ms)
  UNPRED(is_null, dur_us)
  UNPRED(is_null, dur_ns)
  UNPRED(is_null, str)

  // Binary arithmetic
  BINOP(add, i8)
  BINOP(add, i16)
  BINOP(add, i32)
  BINOP(add, i64)
  BINOP(add, u8)
  BINOP(add, u16)
  BINOP(add, u32)
  BINOP(add, u64)
  BINOP(add, f32)
  BINOP(add, f64)
  BINOP(add, dec32)
  BINOP(add, dec64)
  BINOP(add, dec128)
  BINOP(add, dur_D)
  BINOP(add, dur_h)
  BINOP(add, dur_m)
  BINOP(add, dur_s)
  BINOP(add, dur_ms)
  BINOP(add, dur_us)
  BINOP(add, dur_ns)

  BINOP(sub, i8)
  BINOP(sub, i16)
  BINOP(sub, i32)
  BINOP(sub, i64)
  BINOP(sub, u8)
  BINOP(sub, u16)
  BINOP(sub, u32)
  BINOP(sub, u64)
  BINOP(sub, f32)
  BINOP(sub, f64)
  BINOP(sub, dec32)
  BINOP(sub, dec64)
  BINOP(sub, dec128)
  BINOP(sub, dur_D)
  BINOP(sub, dur_h)
  BINOP(sub, dur_m)
  BINOP(sub, dur_s)
  BINOP(sub, dur_ms)
  BINOP(sub, dur_us)
  BINOP(sub, dur_ns)

  BINOP(mul, i8)
  BINOP(mul, i16)
  BINOP(mul, i32)
  BINOP(mul, i64)
  BINOP(mul, u8)
  BINOP(mul, u16)
  BINOP(mul, u32)
  BINOP(mul, u64)
  BINOP(mul, f32)
  BINOP(mul, f64)
  BINOP(mul, dec32)
  BINOP(mul, dec64)
  BINOP(mul, dec128)

  BINOP(div, i8)
  BINOP(div, i16)
  BINOP(div, i32)
  BINOP(div, i64)
  BINOP(div, u8)
  BINOP(div, u16)
  BINOP(div, u32)
  BINOP(div, u64)
  BINOP(div, f32)
  BINOP(div, f64)
  BINOP(div, dec32)
  BINOP(div, dec64)
  BINOP(div, dec128)

  BINOP(mod, i8)
  BINOP(mod, i16)
  BINOP(mod, i32)
  BINOP(mod, i64)
  BINOP(mod, u8)
  BINOP(mod, u16)
  BINOP(mod, u32)
  BINOP(mod, u64)
  BINOP(mod, f32)
  BINOP(mod, f64)
  BINOP(mod, dec32)
  BINOP(mod, dec64)
  BINOP(mod, dec128)

  BINOP(pymod, i8)
  BINOP(pymod, i16)
  BINOP(pymod, i32)
  BINOP(pymod, i64)
  BINOP(pymod, u8)
  BINOP(pymod, u16)
  BINOP(pymod, u32)
  BINOP(pymod, u64)
  BINOP(pymod, f32)
  BINOP(pymod, f64)

  BINOP(pow, f32)
  BINOP(pow, f64)

  // Binary bitwise/logical
  BINOP(bit_and, i8)
  BINOP(bit_and, i16)
  BINOP(bit_and, i32)
  BINOP(bit_and, i64)
  BINOP(bit_and, u8)
  BINOP(bit_and, u16)
  BINOP(bit_and, u32)
  BINOP(bit_and, u64)

  BINOP(bit_or, i8)
  BINOP(bit_or, i16)
  BINOP(bit_or, i32)
  BINOP(bit_or, i64)
  BINOP(bit_or, u8)
  BINOP(bit_or, u16)
  BINOP(bit_or, u32)
  BINOP(bit_or, u64)

  BINOP(bit_xor, i8)
  BINOP(bit_xor, i16)
  BINOP(bit_xor, i32)
  BINOP(bit_xor, i64)
  BINOP(bit_xor, u8)
  BINOP(bit_xor, u16)
  BINOP(bit_xor, u32)
  BINOP(bit_xor, u64)

  BINOP(logical_and, b8)
  BINOP(logical_and, i8)
  BINOP(logical_and, i16)
  BINOP(logical_and, i32)
  BINOP(logical_and, i64)
  BINOP(logical_and, u8)
  BINOP(logical_and, u16)
  BINOP(logical_and, u32)
  BINOP(logical_and, u64)

  // Binary predicates
  BINCMP(equal, b8)
  BINCMP(equal, i8)
  BINCMP(equal, i16)
  BINCMP(equal, i32)
  BINCMP(equal, i64)
  BINCMP(equal, u8)
  BINCMP(equal, u16)
  BINCMP(equal, u32)
  BINCMP(equal, u64)
  BINCMP(equal, f32)
  BINCMP(equal, f64)
  BINCMP(equal, dec32)
  BINCMP(equal, dec64)
  BINCMP(equal, dec128)
  BINCMP(equal, ts_D)
  BINCMP(equal, ts_h)
  BINCMP(equal, ts_m)
  BINCMP(equal, ts_s)
  BINCMP(equal, ts_ms)
  BINCMP(equal, ts_us)
  BINCMP(equal, ts_ns)
  BINCMP(equal, dur_D)
  BINCMP(equal, dur_h)
  BINCMP(equal, dur_m)
  BINCMP(equal, dur_s)
  BINCMP(equal, dur_ms)
  BINCMP(equal, dur_us)
  BINCMP(equal, dur_ns)
  BINCMP(equal, str)

  BINCMP(null_equal, b8)
  BINCMP(null_equal, i8)
  BINCMP(null_equal, i16)
  BINCMP(null_equal, i32)
  BINCMP(null_equal, i64)
  BINCMP(null_equal, u8)
  BINCMP(null_equal, u16)
  BINCMP(null_equal, u32)
  BINCMP(null_equal, u64)
  BINCMP(null_equal, f32)
  BINCMP(null_equal, f64)
  BINCMP(null_equal, dec32)
  BINCMP(null_equal, dec64)
  BINCMP(null_equal, dec128)
  BINCMP(null_equal, ts_D)
  BINCMP(null_equal, ts_h)
  BINCMP(null_equal, ts_m)
  BINCMP(null_equal, ts_s)
  BINCMP(null_equal, ts_ms)
  BINCMP(null_equal, ts_us)
  BINCMP(null_equal, ts_ns)
  BINCMP(null_equal, dur_D)
  BINCMP(null_equal, dur_h)
  BINCMP(null_equal, dur_m)
  BINCMP(null_equal, dur_s)
  BINCMP(null_equal, dur_ms)
  BINCMP(null_equal, dur_us)
  BINCMP(null_equal, dur_ns)
  BINCMP(null_equal, str)

  BINCMP(less, b8)
  BINCMP(less, i8)
  BINCMP(less, i16)
  BINCMP(less, i32)
  BINCMP(less, i64)
  BINCMP(less, u8)
  BINCMP(less, u16)
  BINCMP(less, u32)
  BINCMP(less, u64)
  BINCMP(less, f32)
  BINCMP(less, f64)
  BINCMP(less, dec32)
  BINCMP(less, dec64)
  BINCMP(less, dec128)
  BINCMP(less, ts_D)
  BINCMP(less, ts_h)
  BINCMP(less, ts_m)
  BINCMP(less, ts_s)
  BINCMP(less, ts_ms)
  BINCMP(less, ts_us)
  BINCMP(less, ts_ns)
  BINCMP(less, dur_D)
  BINCMP(less, dur_h)
  BINCMP(less, dur_m)
  BINCMP(less, dur_s)
  BINCMP(less, dur_ms)
  BINCMP(less, dur_us)
  BINCMP(less, dur_ns)
  BINCMP(less, str)

  BINCMP(less_equal, b8)
  BINCMP(less_equal, i8)
  BINCMP(less_equal, i16)
  BINCMP(less_equal, i32)
  BINCMP(less_equal, i64)
  BINCMP(less_equal, u8)
  BINCMP(less_equal, u16)
  BINCMP(less_equal, u32)
  BINCMP(less_equal, u64)
  BINCMP(less_equal, f32)
  BINCMP(less_equal, f64)
  BINCMP(less_equal, dec32)
  BINCMP(less_equal, dec64)
  BINCMP(less_equal, dec128)
  BINCMP(less_equal, ts_D)
  BINCMP(less_equal, ts_h)
  BINCMP(less_equal, ts_m)
  BINCMP(less_equal, ts_s)
  BINCMP(less_equal, ts_ms)
  BINCMP(less_equal, ts_us)
  BINCMP(less_equal, ts_ns)
  BINCMP(less_equal, dur_D)
  BINCMP(less_equal, dur_h)
  BINCMP(less_equal, dur_m)
  BINCMP(less_equal, dur_s)
  BINCMP(less_equal, dur_ms)
  BINCMP(less_equal, dur_us)
  BINCMP(less_equal, dur_ns)
  BINCMP(less_equal, str)

  BINCMP(greater, b8)
  BINCMP(greater, i8)
  BINCMP(greater, i16)
  BINCMP(greater, i32)
  BINCMP(greater, i64)
  BINCMP(greater, u8)
  BINCMP(greater, u16)
  BINCMP(greater, u32)
  BINCMP(greater, u64)
  BINCMP(greater, f32)
  BINCMP(greater, f64)
  BINCMP(greater, dec32)
  BINCMP(greater, dec64)
  BINCMP(greater, dec128)
  BINCMP(greater, ts_D)
  BINCMP(greater, ts_h)
  BINCMP(greater, ts_m)
  BINCMP(greater, ts_s)
  BINCMP(greater, ts_ms)
  BINCMP(greater, ts_us)
  BINCMP(greater, ts_ns)
  BINCMP(greater, dur_D)
  BINCMP(greater, dur_h)
  BINCMP(greater, dur_m)
  BINCMP(greater, dur_s)
  BINCMP(greater, dur_ms)
  BINCMP(greater, dur_us)
  BINCMP(greater, dur_ns)
  BINCMP(greater, str)

  BINCMP(greater_equal, b8)
  BINCMP(greater_equal, i8)
  BINCMP(greater_equal, i16)
  BINCMP(greater_equal, i32)
  BINCMP(greater_equal, i64)
  BINCMP(greater_equal, u8)
  BINCMP(greater_equal, u16)
  BINCMP(greater_equal, u32)
  BINCMP(greater_equal, u64)
  BINCMP(greater_equal, f32)
  BINCMP(greater_equal, f64)
  BINCMP(greater_equal, dec32)
  BINCMP(greater_equal, dec64)
  BINCMP(greater_equal, dec128)
  BINCMP(greater_equal, ts_D)
  BINCMP(greater_equal, ts_h)
  BINCMP(greater_equal, ts_m)
  BINCMP(greater_equal, ts_s)
  BINCMP(greater_equal, ts_ms)
  BINCMP(greater_equal, ts_us)
  BINCMP(greater_equal, ts_ns)
  BINCMP(greater_equal, dur_D)
  BINCMP(greater_equal, dur_h)
  BINCMP(greater_equal, dur_m)
  BINCMP(greater_equal, dur_s)
  BINCMP(greater_equal, dur_ms)
  BINCMP(greater_equal, dur_us)
  BINCMP(greater_equal, dur_ns)
  BINCMP(greater_equal, str)

  // Casts

  CASTOP(to_i32, i32, b8)
  CASTOP(to_i32, i32, i8)
  CASTOP(to_i32, i32, i16)
  CASTOP(to_i32, i32, i32)
  CASTOP(to_i32, i32, i64)
  CASTOP(to_i32, i32, u8)
  CASTOP(to_i32, i32, u16)
  CASTOP(to_i32, i32, u32)
  CASTOP(to_i32, i32, u64)
  CASTOP(to_i32, i32, f32)
  CASTOP(to_i32, i32, f64)

  CASTOP(to_i64, i64, b8)
  CASTOP(to_i64, i64, i8)
  CASTOP(to_i64, i64, i16)
  CASTOP(to_i64, i64, i32)
  CASTOP(to_i64, i64, i64)
  CASTOP(to_i64, i64, u8)
  CASTOP(to_i64, i64, u16)
  CASTOP(to_i64, i64, u32)
  CASTOP(to_i64, i64, u64)
  CASTOP(to_i64, i64, f32)
  CASTOP(to_i64, i64, f64)

  CASTOP(to_u32, u32, b8)
  CASTOP(to_u32, u32, i8)
  CASTOP(to_u32, u32, i16)
  CASTOP(to_u32, u32, i32)
  CASTOP(to_u32, u32, i64)
  CASTOP(to_u32, u32, u8)
  CASTOP(to_u32, u32, u16)
  CASTOP(to_u32, u32, u32)
  CASTOP(to_u32, u32, u64)
  CASTOP(to_u32, u32, f32)
  CASTOP(to_u32, u32, f64)

  CASTOP(to_u64, u64, b8)
  CASTOP(to_u64, u64, i8)
  CASTOP(to_u64, u64, i16)
  CASTOP(to_u64, u64, i32)
  CASTOP(to_u64, u64, i64)
  CASTOP(to_u64, u64, u8)
  CASTOP(to_u64, u64, u16)
  CASTOP(to_u64, u64, u32)
  CASTOP(to_u64, u64, u64)
  CASTOP(to_u64, u64, f32)
  CASTOP(to_u64, u64, f64)

  CASTOP(to_f32, f32, b8)
  CASTOP(to_f32, f32, i8)
  CASTOP(to_f32, f32, i16)
  CASTOP(to_f32, f32, i32)
  CASTOP(to_f32, f32, i64)
  CASTOP(to_f32, f32, u8)
  CASTOP(to_f32, f32, u16)
  CASTOP(to_f32, f32, u32)
  CASTOP(to_f32, f32, u64)
  CASTOP(to_f32, f32, f32)
  CASTOP(to_f32, f32, f64)

  CASTOP(to_f64, f64, b8)
  CASTOP(to_f64, f64, i8)
  CASTOP(to_f64, f64, i16)
  CASTOP(to_f64, f64, i32)
  CASTOP(to_f64, f64, i64)
  CASTOP(to_f64, f64, u8)
  CASTOP(to_f64, f64, u16)
  CASTOP(to_f64, f64, u32)
  CASTOP(to_f64, f64, u64)
  CASTOP(to_f64, f64, f32)
  CASTOP(to_f64, f64, f64)

  // Ternary
  COND_OP(if_else, b8)
  COND_OP(if_else, i8)
  COND_OP(if_else, i16)
  COND_OP(if_else, i32)
  COND_OP(if_else, i64)
  COND_OP(if_else, u8)
  COND_OP(if_else, u16)
  COND_OP(if_else, u32)
  COND_OP(if_else, u64)
  COND_OP(if_else, f32)
  COND_OP(if_else, f64)
  COND_OP(if_else, dec32)
  COND_OP(if_else, dec64)
  COND_OP(if_else, dec128)
  COND_OP(if_else, ts_D)
  COND_OP(if_else, ts_h)
  COND_OP(if_else, ts_m)
  COND_OP(if_else, ts_s)
  COND_OP(if_else, ts_ms)
  COND_OP(if_else, ts_us)
  COND_OP(if_else, ts_ns)
  COND_OP(if_else, dur_D)
  COND_OP(if_else, dur_h)
  COND_OP(if_else, dur_m)
  COND_OP(if_else, dur_s)
  COND_OP(if_else, dur_ms)
  COND_OP(if_else, dur_us)
  COND_OP(if_else, dur_ns)
  COND_OP(if_else, str)

  }  // namespace lite
}  // namespace cudf
