# SPDX-FileCopyrightText: Copyright (c) 2022-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

from typing import Any

class Reducible:
    _SUPPORTED_REDUCTIONS: set

    def sum(self, skipna: bool = True, min_count: int = 0, **kwargs: Any): ...
    def product(
        self, skipna: bool = True, min_count: int = 0, **kwargs: Any
    ): ...
    def min(self, skipna: bool = True, min_count: int = 0, **kwargs: Any): ...
    def max(self, skipna: bool = True, min_count: int = 0, **kwargs: Any): ...
    def count(
        self, skipna: bool = True, min_count: int = 0, **kwargs: Any
    ): ...
    def any(self, skipna: bool = True, min_count: int = 0, **kwargs: Any): ...
    def all(self, skipna: bool = True, min_count: int = 0, **kwargs: Any): ...
    def sum_of_squares(
        self, skipna: bool = True, min_count: int = 0, **kwargs: Any
    ): ...
    def mean(self, skipna: bool = True, min_count: int = 0, **kwargs: Any): ...
    def var(self, skipna: bool = True, min_count: int = 0, **kwargs: Any): ...
    def std(self, skipna: bool = True, min_count: int = 0, **kwargs: Any): ...
    def median(
        self, skipna: bool = True, min_count: int = 0, **kwargs: Any
    ): ...
    def argmax(
        self, skipna: bool = True, min_count: int = 0, **kwargs: Any
    ): ...
    def argmin(
        self, skipna: bool = True, min_count: int = 0, **kwargs: Any
    ): ...
    def nunique(
        self, skipna: bool = True, min_count: int = 0, **kwargs: Any
    ): ...
    def nth(self, skipna: bool = True, min_count: int = 0, **kwargs: Any): ...
    def collect(
        self, skipna: bool = True, min_count: int = 0, **kwargs: Any
    ): ...
    def prod(self, skipna: bool = True, min_count: int = 0, **kwargs: Any): ...
    def idxmin(
        self, skipna: bool = True, min_count: int = 0, **kwargs: Any
    ): ...
    def idxmax(
        self, skipna: bool = True, min_count: int = 0, **kwargs: Any
    ): ...
    def first(
        self, skipna: bool = True, min_count: int = 0, **kwargs: Any
    ): ...
    def last(self, skipna: bool = True, min_count: int = 0, **kwargs: Any): ...
