# SPDX-FileCopyrightText: Copyright (c) 2022, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

class Scannable:
    _SUPPORTED_SCANS: set

    def cumsum(self): ...
    def cumprod(self): ...
    def cummin(self): ...
    def cummax(self): ...
