# SPDX-FileCopyrightText: Copyright (c) 2022-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

from typing import Any

class Scannable:
    _SUPPORTED_SCANS: set

    def cumsum(self, inclusive: bool = True, **kwargs: Any): ...
    def cumprod(self, inclusive: bool = True, **kwargs: Any): ...
    def cummin(self, inclusive: bool = True, **kwargs: Any): ...
    def cummax(self, inclusive: bool = True, **kwargs: Any): ...
    def ewma(self, inclusive: bool = True, **kwargs: Any): ...
