# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from pylibcudf.io.types import (
    CompressionType,
    QuoteStyle,
    SinkInfo,
    SourceInfo,
    TableWithMetadata,
)
from pylibcudf.table import Table
from pylibcudf.types import DataType
from pylibcudf.utils import CudaStreamLike

class CsvReaderOptions:
    def __init__(self): ...
    def set_header(self, header: int): ...
    def set_names(self, col_names: list[str]): ...
    def set_prefix(self, prefix: str): ...
    def set_use_cols_indexes(self, col_indices: list[int]): ...
    def set_use_cols_names(self, col_names: list[str]): ...
    def set_delimiter(self, delimiter: str): ...
    def set_thousands(self, thousands: str): ...
    def set_comment(self, comment: str): ...
    def set_parse_dates(self, val: list[int | str]): ...
    def set_parse_hex(self, val: list[int | str]): ...
    def set_dtypes(self, types: dict[str, DataType] | list[DataType]): ...
    def set_true_values(self, true_values: list[str]): ...
    def set_false_values(self, false_values: list[str]): ...
    def set_na_values(self, na_values: list[str]): ...
    def set_source(self, src: SourceInfo) -> None: ...
    @staticmethod
    def builder(source: SourceInfo) -> CsvReaderOptionsBuilder: ...

class CsvReaderOptionsBuilder:
    def __init__(self): ...
    def compression(
        self, compression: CompressionType
    ) -> CsvReaderOptionsBuilder: ...
    def mangle_dupe_cols(
        self, mangle_dupe_cols: bool
    ) -> CsvReaderOptionsBuilder: ...
    def byte_range_offset(
        self, byte_range_offset: int
    ) -> CsvReaderOptionsBuilder: ...
    def byte_range_size(
        self, byte_range_size: int
    ) -> CsvReaderOptionsBuilder: ...
    def nrows(self, nrows: int) -> CsvReaderOptionsBuilder: ...
    def skiprows(self, skiprows: int) -> CsvReaderOptionsBuilder: ...
    def skipfooter(self, skipfooter: int) -> CsvReaderOptionsBuilder: ...
    def quoting(self, quoting: QuoteStyle) -> CsvReaderOptionsBuilder: ...
    def lineterminator(
        self, lineterminator: str
    ) -> CsvReaderOptionsBuilder: ...
    def quotechar(self, quotechar: str) -> CsvReaderOptionsBuilder: ...
    def decimal(self, decimal: str) -> CsvReaderOptionsBuilder: ...
    def delim_whitespace(
        self, delim_whitespace: bool
    ) -> CsvReaderOptionsBuilder: ...
    def skipinitialspace(
        self, skipinitialspace: bool
    ) -> CsvReaderOptionsBuilder: ...
    def skip_blank_lines(
        self, skip_blank_lines: bool
    ) -> CsvReaderOptionsBuilder: ...
    def doublequote(self, doublequote: bool) -> CsvReaderOptionsBuilder: ...
    def keep_default_na(
        self, keep_default_na: bool
    ) -> CsvReaderOptionsBuilder: ...
    def na_filter(self, na_filter: bool) -> CsvReaderOptionsBuilder: ...
    def dayfirst(self, dayfirst: bool) -> CsvReaderOptionsBuilder: ...
    def delimiter(self, delimiter: str) -> CsvReaderOptionsBuilder: ...
    def build(self) -> CsvReaderOptions: ...

def read_csv(
    options: CsvReaderOptions,
    stream: CudaStreamLike | None = None,
    mr: DeviceMemoryResource | None = None,
) -> TableWithMetadata: ...
def write_csv(
    options: CsvWriterOptions, stream: CudaStreamLike | None = None
): ...

class CsvWriterOptions:
    def __init__(self): ...
    @staticmethod
    def builder(sink: SinkInfo, table: Table) -> CsvWriterOptionsBuilder: ...

class CsvWriterOptionsBuilder:
    def __init__(self): ...
    def names(self, names: list) -> CsvWriterOptionsBuilder: ...
    def na_rep(self, val: str) -> CsvWriterOptionsBuilder: ...
    def include_header(self, val: bool) -> CsvWriterOptionsBuilder: ...
    def rows_per_chunk(self, val: int) -> CsvWriterOptionsBuilder: ...
    def line_terminator(self, term: str) -> CsvWriterOptionsBuilder: ...
    def inter_column_delimiter(
        self, delim: str
    ) -> CsvWriterOptionsBuilder: ...
    def true_value(self, val: str) -> CsvWriterOptionsBuilder: ...
    def false_value(self, val: str) -> CsvWriterOptionsBuilder: ...
    def quoting(self, style: QuoteStyle) -> CsvWriterOptionsBuilder: ...
    def compression(
        self, comp: CompressionType
    ) -> CsvWriterOptionsBuilder: ...
    def compression_block_size(self, size: int) -> CsvWriterOptionsBuilder: ...
    def build(self) -> CsvWriterOptions: ...

def is_supported_write_csv(type: DataType) -> bool: ...
