# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from collections.abc import Mapping, Sequence
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from pylibcudf.expressions import Expression
from pylibcudf.io.parquet_metadata import FileMetaData
from pylibcudf.io.types import (
    CompressionType,
    DictionaryPolicy,
    PartitionInfo,
    SinkInfo,
    SourceInfo,
    StatisticsFreq,
    TableInputMetadata,
    TableWithMetadata,
)
from pylibcudf.table import Table
from pylibcudf.types import TypeId
from pylibcudf.utils import CudaStreamLike

class ParquetReaderOptions:
    def __init__(self): ...
    def set_row_groups(self, row_groups: list[list[int]]): ...
    def set_num_rows(self, nrows: int): ...
    def set_skip_rows(self, skip_rows: int): ...
    def set_columns(self, col_names: list[str]): ...
    def set_column_names(self, col_names: list[str]): ...
    def set_column_indices(self, col_indices: list[int]): ...
    def set_column_field_ids(self, column_field_ids: list[int]): ...
    def set_filter(self, filter: Expression): ...
    def set_source(self, src: SourceInfo) -> None: ...
    def is_enabled_use_jit_filter(self) -> bool: ...
    def enable_case_sensitive_names(self, val: bool) -> None: ...
    def is_enabled_case_sensitive_names(self) -> bool: ...
    def enable_prepend_source_index_column(self, val: bool) -> None: ...
    def is_enabled_prepend_source_index_column(self) -> bool: ...
    @staticmethod
    def builder(source: SourceInfo) -> ParquetReaderOptionsBuilder: ...

class ParquetReaderOptionsBuilder:
    def __init__(self): ...
    def convert_strings_to_categories(
        self, val: bool
    ) -> ParquetReaderOptionsBuilder: ...
    def use_pandas_metadata(
        self, val: bool
    ) -> ParquetReaderOptionsBuilder: ...
    def allow_mismatched_pq_schemas(
        self, val: bool
    ) -> ParquetReaderOptionsBuilder: ...
    def ignore_missing_columns(
        self, val: bool
    ) -> ParquetReaderOptionsBuilder: ...
    def use_arrow_schema(self, val: bool) -> ParquetReaderOptionsBuilder: ...
    def columns(self, col_names: list[str]) -> ParquetReaderOptionsBuilder: ...
    def column_names(
        self, col_names: list[str]
    ) -> ParquetReaderOptionsBuilder: ...
    def column_indices(
        self, col_indices: list[int]
    ) -> ParquetReaderOptionsBuilder: ...
    def column_field_ids(
        self, column_field_ids: list[int]
    ) -> ParquetReaderOptionsBuilder: ...
    def use_jit_filter(
        self, use_jit_filter: bool
    ) -> ParquetReaderOptionsBuilder: ...
    def case_sensitive_names(
        self, val: bool
    ) -> ParquetReaderOptionsBuilder: ...
    def prepend_source_index_column(
        self, val: bool
    ) -> ParquetReaderOptionsBuilder: ...
    def decimal_width(self, width: TypeId) -> ParquetReaderOptionsBuilder: ...
    def build(self) -> ParquetReaderOptions: ...

class ChunkedParquetReader:
    def __init__(
        self,
        options: ParquetReaderOptions,
        stream: CudaStreamLike | None = None,
        mr: DeviceMemoryResource | None = None,
        chunk_read_limit: int = 0,
        pass_read_limit: int = 1024000000,
        parquet_metadatas: Sequence[FileMetaData] | None = None,
    ) -> None: ...
    def has_next(self) -> bool: ...
    def read_chunk(self) -> TableWithMetadata: ...

def read_parquet(
    options: ParquetReaderOptions,
    stream: CudaStreamLike | None = None,
    mr: DeviceMemoryResource | None = None,
    parquet_metadatas: Sequence[FileMetaData] | None = None,
) -> TableWithMetadata: ...

class ParquetWriterOptions:
    def __init__(self): ...
    @staticmethod
    def builder(
        sink: SinkInfo, table: Table
    ) -> ParquetWriterOptionsBuilder: ...
    def set_partitions(self, partitions: list[PartitionInfo]) -> None: ...
    def set_column_chunks_file_paths(
        self, file_paths: Sequence[str]
    ) -> None: ...
    def set_row_group_size_bytes(self, size_bytes: int) -> None: ...
    def set_row_group_size_rows(self, size_rows: int) -> None: ...
    def set_max_page_size_bytes(self, size_bytes: int) -> None: ...
    def set_max_page_size_rows(self, size_rows: int) -> None: ...
    def set_max_dictionary_size(self, size_bytes: int) -> None: ...

class ParquetWriterOptionsBuilder:
    def __init__(self): ...
    def metadata(
        self, metadata: TableInputMetadata
    ) -> ParquetWriterOptionsBuilder: ...
    def key_value_metadata(
        self, metadata: Sequence[Mapping[str, str]]
    ) -> ParquetWriterOptionsBuilder: ...
    def compression(
        self, compression: CompressionType
    ) -> ParquetWriterOptionsBuilder: ...
    def stats_level(
        self, sf: StatisticsFreq
    ) -> ParquetWriterOptionsBuilder: ...
    def int96_timestamps(
        self, enabled: bool
    ) -> ParquetWriterOptionsBuilder: ...
    def write_v2_headers(
        self, enabled: bool
    ) -> ParquetWriterOptionsBuilder: ...
    def page_level_compression(
        self, enabled: bool
    ) -> ParquetWriterOptionsBuilder: ...
    def dictionary_policy(
        self, val: DictionaryPolicy
    ) -> ParquetWriterOptionsBuilder: ...
    def utc_timestamps(self, enabled: bool) -> ParquetWriterOptionsBuilder: ...
    def write_arrow_schema(
        self, enabled: bool
    ) -> ParquetWriterOptionsBuilder: ...
    def row_group_size_rows(self, val: int) -> ParquetWriterOptionsBuilder: ...
    def max_page_size_bytes(self, val: int) -> ParquetWriterOptionsBuilder: ...
    def build(self) -> ParquetWriterOptions: ...

def write_parquet(
    options: ParquetWriterOptions, stream: CudaStreamLike | None = None
) -> memoryview: ...
def is_supported_read_parquet(compression: CompressionType) -> bool: ...
def is_supported_write_parquet(compression: CompressionType) -> bool: ...

class ChunkedParquetWriter:
    def __init__(self): ...
    def close(self, metadata_file_path: list) -> memoryview: ...
    def write(self, table: Table, partitions_info: object = None) -> None: ...
    @staticmethod
    def from_options(
        options: ChunkedParquetWriterOptions,
        stream: CudaStreamLike | None = None,
    ) -> ChunkedParquetWriter: ...

class ChunkedParquetWriterOptions:
    def __init__(self): ...
    def set_dictionary_policy(self, policy: DictionaryPolicy) -> None: ...
    @staticmethod
    def builder(sink: SinkInfo) -> ChunkedParquetWriterOptionsBuilder: ...

class ChunkedParquetWriterOptionsBuilder:
    def __init__(self): ...
    def metadata(
        self, metadata: TableInputMetadata
    ) -> ChunkedParquetWriterOptionsBuilder: ...
    def key_value_metadata(
        self, metadata: Sequence[Mapping[str, str]]
    ) -> ChunkedParquetWriterOptionsBuilder: ...
    def compression(
        self, compression: CompressionType
    ) -> ChunkedParquetWriterOptionsBuilder: ...
    def stats_level(
        self, sf: StatisticsFreq
    ) -> ChunkedParquetWriterOptionsBuilder: ...
    def row_group_size_bytes(
        self, val: int
    ) -> ChunkedParquetWriterOptionsBuilder: ...
    def row_group_size_rows(
        self, val: int
    ) -> ChunkedParquetWriterOptionsBuilder: ...
    def max_page_size_bytes(
        self, val: int
    ) -> ChunkedParquetWriterOptionsBuilder: ...
    def max_page_size_rows(
        self, val: int
    ) -> ChunkedParquetWriterOptionsBuilder: ...
    def max_dictionary_size(
        self, val: int
    ) -> ChunkedParquetWriterOptionsBuilder: ...
    def write_arrow_schema(
        self, enabled: bool
    ) -> ChunkedParquetWriterOptionsBuilder: ...
    def build(self) -> ChunkedParquetWriterOptions: ...

def merge_row_group_metadata(metdata_list: list) -> memoryview: ...
