# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

from pylibcudf.io.types import SourceInfo
from pylibcudf.types import DataType

try:
    from collections.abc import Buffer
except ImportError:
    from typing_extensions import Buffer

__all__ = [
    "FileMetaData",
    "ParquetColumnSchema",
    "ParquetMetadata",
    "ParquetSchema",
    "read_parquet_footers",
    "read_parquet_metadata",
]

class ParquetColumnSchema:
    def name(self) -> str: ...
    def num_children(self) -> int: ...
    def child(self, idx: int) -> ParquetColumnSchema: ...
    def children(self) -> list[ParquetColumnSchema]: ...

class ParquetSchema:
    def root(self) -> ParquetColumnSchema: ...
    def column_types(self) -> dict[str, DataType]: ...

class ParquetMetadata:
    def schema(self) -> ParquetSchema: ...
    def num_rows(self) -> int: ...
    def num_rowgroups(self) -> int: ...
    def num_rowgroups_per_file(self) -> list[int]: ...
    def metadata(self) -> dict[str, str]: ...
    def rowgroup_metadata(self) -> list[dict[str, int]]: ...
    def columnchunk_metadata(self) -> dict[str, list[int]]: ...

class FileMetaData:
    @classmethod
    def from_bytes(cls, footer_bytes: Buffer) -> FileMetaData: ...
    @property
    def version(self) -> int: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def created_by(self) -> str: ...

def read_parquet_metadata(src_info: SourceInfo) -> ParquetMetadata: ...
def read_parquet_footers(src_info: SourceInfo) -> list[FileMetaData]: ...
