# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

from pylibcudf.io.types import SourceInfo
from pylibcudf.types import DataType

try:
    from collections.abc import Buffer
except ImportError:
    from typing_extensions import Buffer

__all__ = [
    "ColumnChunk",
    "ColumnChunkMetaData",
    "FileMetaData",
    "ParquetColumnSchema",
    "ParquetMetadata",
    "ParquetSchema",
    "RowGroup",
    "SortingColumn",
    "read_parquet_footers",
    "read_parquet_metadata",
]

class ParquetColumnSchema:
    def name(self) -> str: ...
    def num_children(self) -> int: ...
    def child(self, idx: int) -> ParquetColumnSchema: ...
    def children(self) -> list[ParquetColumnSchema]: ...

class ParquetSchema:
    def root(self) -> ParquetColumnSchema: ...
    def column_types(self) -> dict[str, DataType]: ...

class ParquetMetadata:
    def schema(self) -> ParquetSchema: ...
    def num_rows(self) -> int: ...
    def num_rowgroups(self) -> int: ...
    def num_rowgroups_per_file(self) -> list[int]: ...
    def metadata(self) -> dict[str, str]: ...
    def rowgroup_metadata(self) -> list[dict[str, int]]: ...
    def columnchunk_metadata(self) -> dict[str, list[int]]: ...

class FileMetaData:
    @classmethod
    def from_bytes(cls, footer_bytes: Buffer) -> FileMetaData: ...
    @property
    def version(self) -> int: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def created_by(self) -> str: ...
    @property
    def row_groups(self) -> list[RowGroup]: ...
    @property
    def row_group_num_rows(self) -> list[int]: ...

class SortingColumn:
    @property
    def column_idx(self) -> int: ...
    @property
    def descending(self) -> bool: ...
    @property
    def nulls_first(self) -> bool: ...

class ColumnChunk:
    @property
    def file_path(self) -> str: ...
    @property
    def file_offset(self) -> int: ...
    @property
    def offset_index_offset(self) -> int: ...
    @property
    def offset_index_length(self) -> int: ...
    @property
    def column_index_offset(self) -> int: ...
    @property
    def column_index_length(self) -> int: ...
    @property
    def schema_idx(self) -> int: ...
    @property
    def meta_data(self) -> ColumnChunkMetaData: ...

class ColumnChunkMetaData:
    @property
    def path_in_schema(self) -> list[str]: ...
    @property
    def num_values(self) -> int: ...
    @property
    def total_uncompressed_size(self) -> int: ...
    @property
    def total_compressed_size(self) -> int: ...

class RowGroup:
    @property
    def columns(self) -> list[ColumnChunk]: ...
    @property
    def total_byte_size(self) -> int: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def sorting_columns(self) -> list[SortingColumn] | None: ...
    @property
    def file_offset(self) -> int | None: ...
    @property
    def total_compressed_size(self) -> int | None: ...
    @property
    def ordinal(self) -> int | None: ...

def read_parquet_metadata(src_info: SourceInfo) -> ParquetMetadata: ...
def read_parquet_footers(src_info: SourceInfo) -> list[FileMetaData]: ...
