# Copyright (c) 2024, NVIDIA CORPORATION.

from collections.abc import Mapping

from pylibcudf.io.types import SourceInfo

class ParquetColumnSchema:
    def __init__(self): ...
    def name(self) -> str: ...
    def num_children(self) -> int: ...
    def child(self, idx: int) -> ParquetColumnSchema: ...
    def children(self) -> list[ParquetColumnSchema]: ...

class ParquetSchema:
    def __init__(self): ...
    def root(self) -> ParquetColumnSchema: ...

class ParquetMetadata:
    def __init__(self): ...
    def schema(self) -> ParquetSchema: ...
    def num_rows(self) -> int: ...
    def num_rowgroups(self) -> int: ...
    def metadata(self) -> Mapping[str, str]: ...
    def rowgroup_metadata(self) -> list[Mapping[str, int]]: ...

def read_parquet_metadata(src_info: SourceInfo) -> ParquetMetadata: ...
