# Usage:
#   conda build -c defaults -c conda-forge .
package:
  name: pygdf
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - PYGDF_BUILD_NO_GPU_TEST

requirements:
  build:
    - python
    - setuptools
    - numba>=0.40.0dev
  run:
    - python
    - setuptools
    - libgdf 0.1.0a3.*
    - libgdf_cffi 0.1.0a3.*
    - pandas>=0.20.3
    - numba>=0.40.0dev

test:
  requires:
    - distributed >=1.22.1
    - pytest
  imports:
    - pygdf

about:
  home: http://gpuopenanalytics.com/
  license: Apache
  # license_file: LICENSE
  summary: GPU Dataframe core library
