from __future__ import print_function
import ctypes
from contextlib import contextmanager

import pytest

import numpy as np
from numba import cuda

from libgdf_cffi import ffi, libgdf

from .utils import new_column, unwrap_devary, get_dtype


@contextmanager
def _make_hash_input(hash_input, ncols):
    ci = []

    for i in range(ncols):
        d_input = cuda.to_device(hash_input[i])
        col_input = new_column()
        libgdf.gdf_column_view(col_input, unwrap_devary(d_input), ffi.NULL,
                            hash_input[i].size, get_dtype(d_input.dtype))
        ci.append(col_input)

    yield ci

def _call_hash_multi(api, ncols, col_input, magic):
    hash_result_ptr = ffi.new("gdf_join_result_type**", None)

    api(ncols, col_input, magic, hash_result_ptr)
    hash_result = hash_result_ptr[0]
    print('hash_result', hash_result)

    dataptr = libgdf.gdf_join_result_data(hash_result)
    print(dataptr)
    datasize = libgdf.gdf_join_result_size(hash_result)
    print(datasize)

    addr = ctypes.c_uint64(int(ffi.cast("uintptr_t", dataptr)))
    print(hex(addr.value))
    memptr = cuda.driver.MemoryPointer(context=cuda.current_context(),
                                       pointer=addr, size=4 * datasize)
    print(memptr)
    ary = cuda.devicearray.DeviceNDArray(shape=(datasize,), strides=(4,),
                                         dtype=np.dtype(np.int32),
                                         gpu_data=memptr)

    hashed_idx = ary.copy_to_host()
    print(hashed_idx)

    libgdf.gdf_join_result_free(hash_result)
    return hashed_idx


multi_params_dtypes = [np.int32, np.int64]


@pytest.mark.parametrize('dtype', multi_params_dtypes)
def test_hashing(dtype):
    # Make data
    hash_input = np.array([[0, 0, 4, 5, 5], [1, 1, 2, 3, 4], [1, 1, 3, 1, 2]], dtype=dtype)

    ncols = 3
    magic = 0
    
    with _make_hash_input(hash_input, ncols) as (col_input):
        # Join
        hashed_idx = _call_hash_multi(libgdf.gdf_hash, ncols, col_input, magic)

    # Check answer
    # Can be generated by:

    # print result
    print(hashed_idx)
            