# Copyright (c) 2024, NVIDIA CORPORATION.

from pylibcudf.column import Column
from pylibcudf.scalar import Scalar

def capitalize(input: Column, delimiters: Scalar | None = None) -> Column: ...
def title(input: Column) -> Column: ...
def is_title(input: Column) -> Column: ...
