# Copyright (c) 2024, NVIDIA CORPORATION.

from pylibcudf.column import Column

def to_lower(input: Column) -> Column: ...
def to_upper(input: Column) -> Column: ...
def swapcase(input: Column) -> Column: ...
