# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

from enum import IntEnum

from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from pylibcudf.column import Column
from pylibcudf.scalar import Scalar
from pylibcudf.utils import CudaStreamLike

class StringCharacterTypes(IntEnum):
    DECIMAL = ...
    NUMERIC = ...
    DIGIT = ...
    ALPHA = ...
    SPACE = ...
    UPPER = ...
    LOWER = ...
    ALPHANUM = ...
    CASE_TYPES = ...
    ALL_TYPES = ...

def all_characters_of_type(
    source_strings: Column,
    types: StringCharacterTypes,
    verify_types: StringCharacterTypes,
    stream: CudaStreamLike | None = None,
    mr: DeviceMemoryResource | None = None,
) -> Column: ...
def filter_characters_of_type(
    source_strings: Column,
    types_to_remove: StringCharacterTypes,
    replacement: Scalar,
    types_to_keep: StringCharacterTypes,
    stream: CudaStreamLike | None = None,
    mr: DeviceMemoryResource | None = None,
) -> Column: ...
