# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
from enum import IntEnum

class SideType(IntEnum):
    LEFT = ...
    RIGHT = ...
    BOTH = ...
