#!/usr/bin/env python3
"""Generate compressed Regex IR character-class ranges from cuDF's Unicode table."""

from __future__ import annotations

import argparse
import pathlib
import re


def parse_flags(path: pathlib.Path) -> list[int]:
    """Read the 65,536 character flags from cuDF's generated header."""
    text = path.read_text(encoding="utf-8")
    match = re.search(r"g_character_codepoint_flags\[\] = \{(.*?)\};", text, re.DOTALL)
    if match is None:
        raise ValueError(f"could not find g_character_codepoint_flags in {path}")
    values = [int(value) for value in match.group(1).replace("\n", " ").split(",") if value.strip()]
    if len(values) != 65_536:
        raise ValueError(f"expected 65,536 flags, found {len(values)}")
    return values


def compress(values: list[int], mask: int) -> list[tuple[int, int]]:
    """Compress code points having any selected flag into inclusive ranges."""
    ranges: list[tuple[int, int]] = []
    begin: int | None = None
    for codepoint, flags in enumerate([*values, 0]):
        selected = (flags & mask) != 0
        if selected and begin is None:
            begin = codepoint
        elif not selected and begin is not None:
            ranges.append((begin, codepoint - 1))
            begin = None
    return ranges


def render_array(name: str, ranges: list[tuple[int, int]]) -> str:
    """Render one C++ range array."""
    entries = "\n".join(f"  {{{first:#08x}U, {last:#08x}U}}," for first, last in ranges)
    return f"inline constexpr unicode_data_range {name}[] = {{\n{entries}\n}};\n"


def main() -> None:
    """Parse arguments and write the generated include."""
    parser = argparse.ArgumentParser()
    parser.add_argument("char_flags", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    values = parse_flags(args.char_flags)
    output = """/*
 * Derived from NVIDIA RAPIDS cuDF's Apache-2.0-licensed char_flags.h.
 * Generated by scripts/generate_cudf_unicode_ranges.py; do not edit.
 */

struct unicode_data_range {
  std::uint32_t first;
  std::uint32_t last;
};

"""
    output += render_array("cudf_unicode_word_ranges", compress(values, 0x0F))
    output += "\n"
    output += render_array("cudf_unicode_digit_ranges", compress(values, 0x04))
    output += "\n"
    output += render_array("cudf_unicode_space_ranges", compress(values, 0x10))
    args.output.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
