# Copyright (c) 2024, NVIDIA CORPORATION.

from pylibcudf.column import Column

def ipv4_to_integers(input: Column) -> Column: ...
def integers_to_ipv4(integers: Column) -> Column: ...
def is_ipv4(input: Column) -> Column: ...
