# Copyright (c) 2024, NVIDIA CORPORATION.

from pylibcudf.column import Column
from pylibcudf.types import DataType

def to_floats(strings: Column, output_type: DataType) -> Column: ...
def from_floats(floats: Column) -> Column: ...
def is_float(input: Column) -> Column: ...
