# SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Label external issues and PRs

on:
  issues:
    types:
      - opened

  pull_request_target:
    types:
      - opened

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  Label-Issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.event_name == 'issues'
    steps:
      - name: add-external-labels
        # Only run if the issue author is not part of RAPIDS
        if: ${{ ! contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.issue.author_association)}}
        run: |
          echo ${{ github.event.issue.author_association }}
          issue_url=${{ github.event.issue.html_url }}
          gh issue edit ${issue_url} --add-label "External"
        continue-on-error: true

  Label-PR:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    if: github.event_name == 'pull_request_target'
    steps:
      - name: add-external-labels
        # Only run if the issue author is not part of RAPIDS
        if: ${{ ! contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.pull_request.author_association)}}
        run: |
            echo ${{ github.event.pull_request.author_association }}
            pr_url=${{ github.event.pull_request.html_url }}
            gh issue edit ${pr_url} --add-label "External"
        continue-on-error: true
