name: JNI Docker Build

on:
  workflow_dispatch: # manual trigger only

concurrency:
  group: jni-docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    if: github.repository == 'rapidsai/cudf'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set ENVs
        run: |
          echo "IMAGE_NAME=gpuci/cudf-jni-build" >> $GITHUB_ENV
          echo "IMAGE_REF=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "IMAGE_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: java/ci/Dockerfile.centos7
          tags: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_REF }},${{ env.IMAGE_NAME }}:${{ env.IMAGE_SHA }}"
