name: spark-rapids-jni

on:
  workflow_call:

jobs:
  spark-rapids-jni-build:
    runs-on: linux-amd64-cpu8
    container:
      image: rapidsai/ci-spark-rapids-jni:rockylinux8-cuda12.9.1
    steps:
      - uses: actions/checkout@v4
        with:
          repository: NVIDIA/spark-rapids-jni
          submodules: recursive
          ref: ${{ github.event.pull_request.base.ref }}
      - uses: actions/checkout@v4
        with:
          path: thirdparty/cudf
      - name: "Build spark-rapids-jni"
        run: |
          mkdir target
          source build/env.sh && CMAKE_CUDA_ARCHITECTURES=90 LIBCUDF_DEPENDENCY_MODE=latest USE_GDS=on ${sclCMD} build/buildcpp.sh
