name: spark-rapids-jni

on:
  workflow_call:

jobs:
  spark-rapids-jni-build:
    runs-on: linux-amd64-cpu8
    container:
      image: rapidsai/ci-spark-rapids-jni:rockylinux8-cuda12.2.0
    steps:
      - uses: actions/checkout@v4
        with:
          repository: NVIDIA/spark-rapids-jni
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          path: thirdparty/cudf
      - name: "Build spark-rapids-jni"
        run: |
          mkdir target
          GPU_ARCHS=90 LIBCUDF_DEPENDENCY_MODE=latest USE_GDS=on scl enable gcc-toolset-11 build/buildcpp.sh
