name: Trigger Breaking Change Notifications

# `zizmor` always flags these triggers because they are easy to use
# incorrectly. These usages are ok and don't execute any PR-specific
# code (and so aren't susceptible to exploits from forked PRs)
on: # zizmor: ignore[dangerous-triggers]
  pull_request_target:
    types:
      - closed
      - reopened
      - labeled
      - unlabeled

permissions: {}

jobs:
  trigger-notifier:
    if: contains(github.event.pull_request.labels.*.name, 'breaking')
    permissions:
      contents: read
    uses: rapidsai/shared-workflows/.github/workflows/breaking-change-alert.yaml@test-gh200
    secrets:
      slack-webhook-url: ${{ secrets.NV_SLACK_BREAKING_CHANGE_NOTIFIER_APP }}
    with:
      sender_login: ${{ github.event.sender.login }}
      sender_avatar: ${{ github.event.sender.avatar_url }}
      repo: ${{ github.repository }}
      pr_number: ${{ github.event.pull_request.number }}
      pr_title: "${{ github.event.pull_request.title }}"
      pr_body: "${{ github.event.pull_request.body || '_Empty PR description_' }}"
      pr_base_ref: ${{ github.event.pull_request.base.ref }}
      pr_author: ${{ github.event.pull_request.user.login }}
      event_action: ${{ github.event.action }}
      pr_merged: ${{ github.event.pull_request.merged }}
